{
 "title": "Corona",
 "description": "This dashboard will provide global COVID-19 information.",
 "time": { "from": "now/y", "to": "now" },
 "panels": [
  { "title": "World", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Confirmed (x1000)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deaths (x1000)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recovered (x1000)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Remaining (x1000)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT (sum(Confirmed)-sum(Recovered)-sum(Deaths))/1000 FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE $timeFilter GROUP BY time(24h) fill(null)\n",
     "select": [
      [
       { "params": [ "recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fatality Ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Deaths\") *100 / sum(\"Confirmed\") FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "*100 / sum(\"Confirmed\")"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recovery Ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Recovered\") * 100 / sum(\"Confirmed\" FROM \"covid19\".\"autogen\".\"Corona\" WHERE $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "* 100 / sum(\"Confirmed\")"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Confirmed",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT last(\"Confirmed\") AS \"metric\" FROM \"covid19\".\"autogen\".\"Corona\" WHERE $timeFilter GROUP BY \"country\", \"lat\", \"long\"",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT last(\"Deaths\") AS \"metric\" FROM \"autogen\".\"Corona\" WHERE $timeFilter GROUP BY time(24h), \"country\", \"lat\", \"long\"",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Recovered\") FROM \"covid19\".\"autogen\".\"Corona\"  GROUP BY  \"lat\", \"long\"",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": " SELECT sum(\"Confirmed\") AS \"Confirmed\", sum(\"Deaths\") AS \"Deaths\", sum(\"Recovered\") AS \"Recovered\", \n100*sum(Deaths)/sum(Confirmed) as \"Fatality_Ratio\", 100*sum(Recovered)/sum(Confirmed) as \"Recovery_Ratio\", \nsum(\"Confirmed\")-sum(Deaths)-sum(Recovered) as \"Remaining\" FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE $timeFilter GROUP BY time(24h) fill(previous)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Confirmed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(ConfirmedNew) AS \"Confirmed\", sum(DeathsNew) AS \"Deaths\", sum(RecoveredNew) AS \"Recovered\", 100*sum(DeathsNew)/sum(ConfirmedNew) as \"Fatality_Ratio\", 100*sum(RecoveredNew)/sum(ConfirmedNew) as \"Recovery_Ratio\", sum(ConfirmedNew)-sum(DeathsNew)-sum(RecoveredNew) as \"Remaining\" \nFROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE $timeFilter GROUP BY time(24h) fill(previous)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Confirmed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Confirmed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Remaining",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Confirmed\") -sum(Death)-sum(Recovered) FROM \"covid19\".\"autogen\".\"Corona\" WHERE $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "-sum(\"Deaths\")-sum(\"Recovered\")"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Confirmed /d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "ConfirmedNew" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deaths /d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "DeathsNew" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recovered /d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "RecoveredNew" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Remaining /d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Confirmed\") -sum(Death)-sum(Recovered) FROM \"covid19\".\"autogen\".\"Corona\" WHERE $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "ConfirmedNew" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "-sum(\"DeathsNew\")-sum(\"RecoveredNew\")"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  { "title": "France", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "France /w",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "96h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Confirmed\") FROM \"covid19\".\"autogen\".\"Corona\" WHERE (\"country\" = 'Germany') AND $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "ConfirmedNew" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "France" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "96h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "DeathsNew" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "France" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "96h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "RecoveredNew" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "France" }
     ]
    },
    {
     "alias": "Deaths (mean)",
     "groupBy": [
      { "params": [ "96h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT mean(DeathsNew) FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE (\"country\" = 'France') AND $timeFilter GROUP BY time(96h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "RecoveredNew" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "France" }
     ]
    }
   ]
  },
  {
   "title": "Confirmed Population Ratio France",
   "type": "singlestat",
   "description": "Percentage of the French population positive tested on Covid19.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 51 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT last(\"Confirmed\")  * 100 / 67063703  FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE (\"country\" = 'France') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 100 / 82927922 " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    }
   ]
  },
  {
   "title": "Death Population Ratio France",
   "type": "singlestat",
   "description": "Percentage of the French population died on Covid19.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 51 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT last(\"Deaths\")  * 100 / 67063703  FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE (\"country\" = 'France') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 100 / 82927922 " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    }
   ]
  },
  {
   "title": "Death Rate France",
   "type": "singlestat",
   "description": "Death rate of confirmed COVID-19 infections in France.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 51 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT 100*sum(\"Recovered\")/sum(Confirmed) FROM \"covid19\".\"autogen\".\"Corona\" WHERE $timeFilter GROUP BY time(24h) fill(null)\n",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         " * 100 / \"Confirmed\""
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "France" }
     ]
    }
   ]
  },
  { "title": "OtherCountries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Germany",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Confirmed\") FROM \"covid19\".\"autogen\".\"Corona\" WHERE (\"country\" = 'Germany') AND $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    }
   ]
  },
  {
   "title": "Italy",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Confirmed\") FROM \"covid19\".\"autogen\".\"Corona\" WHERE (\"country\" = 'Germany') AND $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    }
   ]
  },
  {
   "title": "China",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Confirmed\") FROM \"covid19\".\"autogen\".\"Corona\" WHERE (\"country\" = 'Germany') AND $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    }
   ]
  },
  {
   "title": "Global Population Confirmed Ratio",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 58 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT 100* sum(Confirmed)/ 7781492808 FROM \"covid19\".\"autogen\".\"Corona\" WHERE $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * 100 / 7781492808" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
     "options": {
      "content": "\n# For free\nThanks to CSSEGISandData for providing figures on an daily base via https://github.com/CSSEGISandData/COVID-19.\n\nThe information of population End 2019 have been taken from https://databank.worldbank.org/reports.aspx?source=2&series=SP.POP.TOTL&country=#advancedDownloadOptions.\n\napp.js to download the files, convert and upload the information int an influxDB is available on https://github.com/smartcuc/COVID-19.\n\nSponsored by my\n\n\n\n\n\n"
     },
     "targets": [
      {
       "alias": "Confirmed",
       "groupBy": [
        { "params": [ "24h" ], "type": "time" },
        { "params": [ "country" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "CoronaNew",
       "query": "SELECT sum(\"Confirmed\") FROM \"covid19\".\"autogen\".\"Corona\" WHERE (\"country\" = 'Germany') AND $timeFilter GROUP BY time(24h), \"country\" fill(null)",
       "select": [
        [
         { "params": [ "Confirmed" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "country", "operator": "=", "value": "Italy" }
       ]
      },
      {
       "alias": "Deaths",
       "groupBy": [
        { "params": [ "24h" ], "type": "time" },
        { "params": [ "country" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "CoronaNew",
       "select": [
        [
         { "params": [ "Deaths" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "country", "operator": "=", "value": "Italy" }
       ]
      },
      {
       "alias": "Recovered",
       "groupBy": [
        { "params": [ "24h" ], "type": "time" },
        { "params": [ "country" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "CoronaNew",
       "select": [
        [
         { "params": [ "Recovered" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "country", "operator": "=", "value": "Italy" }
       ]
      }
     ]
    }
   ]
  }
 ]
}