{
 "title": "Tidhome-Mobile-W",
 "description": "Power Consumption Graphs",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Periode",
   "type": "stat",
   "description": "High/Low power cost period",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensors_teleinfo_PTEC_int @now()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total (W)",
   "type": "gauge",
   "description": "Current Total Power consumption",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sensors_teleinfo_PAPP @ now()", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consumers (W)",
   "type": "gauge",
   "description": "Largest consumers: Car, Water heating, Electric heating",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensors_zigbee_power_l1{location=\"C01~Garage~PowerMeter\"} @ now()",
     "legendFormat": "Car"
    },
    {
     "expr": "sensors_zigbee_power_l2{location=\"C01~Garage~PowerMeter\"} @ now()",
     "legendFormat": "Water"
    },
    {
     "expr": "sensors_zigbee_power_l3{location=\"C01~Garage~PowerMeter\"} @ now()",
     "legendFormat": "Heaters"
    },
    {
     "expr": "sensors_ccost_PAPP{location=\"cc-0-Non-chauffage\"} @ now()",
     "legendFormat": "Non-Heaters"
    }
   ]
  },
  {
   "title": "Outlets (W)",
   "type": "gauge",
   "description": "Current Power on outlets",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensors_zigbee_power{location=~\"P.+\"} @ now()",
     "legendFormat": "{{location}}"
    }
   ]
  }
 ]
}