{
 "title": "Tidhome-Mobile-kWh",
 "description": "Power Consumption Graphs",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "kWhBase", "label": "kWhHP", "query": "0.2062" },
   { "name": "kWhHP", "label": "kWhHP", "query": "0.2228" },
   { "name": "kWhHC", "label": "kWhHC", "query": "0.1615" },
   { "name": "kWhTBHC", "label": "kWhTBHC", "query": "0.1044" },
   { "name": "kWhTBHP", "label": "kWhTBH9", "query": "0.13572" },
   { "name": "kWhTWHC", "label": "kWhTWHC", "query": "0.12336" },
   { "name": "kWhTWHP", "label": "kWhTWHP", "query": "0.16416" },
   { "name": "kWhTRHC", "label": "kWhTRHC", "query": "0.13164" },
   { "name": "kWhTRHP", "label": "kWhTRHP", "query": "0.73116" },
   { "name": "kWhZFEHC", "label": "kWhZFEHC", "query": "0.1464" },
   { "name": "kWhZFEHP", "label": "kWhZFEHP", "query": "0.2460" },
   { "name": "kWhZFSHC", "label": "kWhZFSHC", "query": "0.2460" },
   { "name": "kWhZFSHP", "label": "kWhZFSHP", "query": "0.7324" },
   { "name": "day1", "label": "1 Day", "query": "1d" },
   { "name": "day7", "label": "7 Day", "query": "7d" },
   { "name": "day30", "label": "30 Day", "query": "30d" },
   { "name": "day60", "label": "60 Day", "query": "60d" },
   { "name": "day180", "label": "180 Day", "query": "180d" },
   { "name": "day365", "label": "365 Day", "query": "200d" },
   {
    "name": "nbDays",
    "label": "Days in Donut",
    "query": "1d,7d,15d,30d,60d,90d,180d,365d"
   },
   { "name": "donutValueAs", "label": "Donut Value As", "query": "percent,kWh,€" },
   { "name": "timelineRange", "label": "Timeline Range", "query": "1h,1d,1w" },
   { "name": "timelineTotal", "label": "Timeline Total", "query": "kWh,tempo,blue,base" }
  ]
 },
 "panels": [
  {
   "title": "Cost (€)",
   "type": "stat",
   "description": "Costs computed with Low/High hours energy prices",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @end() offset $day1)) / 1000) * $kWhTBHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_BBRHPJB{} @end() offset $day1)) / 1000) * $kWhTBHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @end() offset $day1)) / 1000) * $kWhTWHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @end() offset $day1)) / 1000) * $kWhTWHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @end() offset $day1)) / 1000) * $kWhTRHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @end() offset $day1)) / 1000) * $kWhTRHP))",
     "legendFormat": "$day1"
    },
    {
     "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @end() offset $day7)) / 1000) * $kWhTBHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_BBRHPJB{} @end() offset $day7)) / 1000) * $kWhTBHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @end() offset $day7)) / 1000) * $kWhTWHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @end() offset $day7)) / 1000) * $kWhTWHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @end() offset $day7)) / 1000) * $kWhTRHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @end() offset $day7)) / 1000) * $kWhTRHP))",
     "legendFormat": "$day7"
    },
    {
     "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @end() offset $day30)) / 1000) * $kWhTBHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_BBRHPJB{} @end() offset $day30)) / 1000) * $kWhTBHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @end() offset $day30)) / 1000) * $kWhTWHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @end() offset $day30)) / 1000) * $kWhTWHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @end() offset $day30)) / 1000) * $kWhTRHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @end() offset $day30)) / 1000) * $kWhTRHP))",
     "legendFormat": "$day30"
    },
    {
     "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @end() offset $day60)) / 1000) * $kWhTBHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_BBRHPJB{} @end() offset $day60)) / 1000) * $kWhTBHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @end() offset $day60)) / 1000) * $kWhTWHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @end() offset $day60)) / 1000) * $kWhTWHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @end() offset $day60)) / 1000) * $kWhTRHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @end() offset $day60)) / 1000) * $kWhTRHP))",
     "legendFormat": "$day60"
    },
    {
     "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_HCHC{} @end() offset $day365)) / 1000) * $kWhTBHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_HCHP{} @end() offset $day365)) / 1000) * $kWhTBHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @end() offset $day365)) / 1000) * $kWhTWHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @end() offset $day365)) / 1000) * $kWhTWHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @end() offset $day365)) / 1000) * $kWhTRHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @end() offset $day365)) / 1000) * $kWhTRHP))",
     "legendFormat": "$day7"
    },
    {
     "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_HCHC{} @ 1672552800)) / 1000) * $kWhTBHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_HCHP{} @ 1672552800)) / 1000) * $kWhTBHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @ 1672552800)) / 1000) * $kWhTWHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @ 1672552800)) / 1000) * $kWhTWHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @ 1672552800)) / 1000) * $kWhTRHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @ 1672552800)) / 1000) * $kWhTRHP))",
     "legendFormat": "$day7"
    }
   ]
  },
  {
   "title": "$nbDays days ($donutValueAs)",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "(sensors_teleinfo_BBRHPJB{db=\"sensors\",location=\"main\"} @ now() - sensors_teleinfo_BBRHPJB{db=\"sensors\",location=\"main\"} offset $nbDays) / 1000",
     "legendFormat": "HPJB"
    },
    {
     "expr": "(sensors_teleinfo_BBRHPJW{db=\"sensors\",location=\"main\"} @ now() - sensors_teleinfo_BBRHPJW{db=\"sensors\",location=\"main\"} offset $nbDays) / 1000",
     "legendFormat": "HPJW"
    },
    {
     "expr": "(sensors_teleinfo_BBRHPJR{db=\"sensors\",location=\"main\"} @ now() - sensors_teleinfo_BBRHPJR{db=\"sensors\",location=\"main\"} offset $nbDays) / 1000",
     "legendFormat": "HPJR"
    },
    { "expression": "$HPJB + $HPJW + $HPJR", "type": "math" },
    {
     "expr": "(sensors_teleinfo_BBRHCJB{db=\"sensors\",location=\"main\"} - sensors_teleinfo_BBRHCJB{db=\"sensors\",location=\"main\"} offset $nbDays) / 1000",
     "legendFormat": "HCJB"
    },
    {
     "expr": "(sensors_teleinfo_BBRHCJW{db=\"sensors\",location=\"main\"} - sensors_teleinfo_BBRHCJW{db=\"sensors\",location=\"main\"} offset $nbDays) / 1000",
     "legendFormat": "HCJW"
    },
    {
     "expr": "(sensors_teleinfo_BBRHCJR{db=\"sensors\",location=\"main\"} - sensors_teleinfo_BBRHCJR{db=\"sensors\",location=\"main\"} offset $nbDays) / 1000",
     "legendFormat": "HCJR"
    },
    { "expression": "$HCJB + $HCJW + $HCJR", "type": "math" },
    {
     "expr": "avg(sensors_zigbee_energy_l1{location=\"C01~Garage~PowerMeter\"} - (sensors_zigbee_energy_l1{location=\"C01~Garage~PowerMeter\"} offset $nbDays))",
     "legendFormat": "Car"
    },
    {
     "expr": "avg(sensors_zigbee_energy_l2{location=\"C01~Garage~PowerMeter\"} - (sensors_zigbee_energy_l2{location=\"C01~Garage~PowerMeter\"} offset $nbDays))",
     "legendFormat": "Water"
    },
    {
     "expr": "avg(sensors_zigbee_energy_l3{location=\"C01~Garage~PowerMeter\"} - (sensors_zigbee_energy_l3{location=\"C01~Garage~PowerMeter\"} offset $nbDays))",
     "legendFormat": "Heaters"
    },
    {
     "expr": "sensors_zigbee_energy{location=~\"P.*\"} - (sensors_zigbee_energy{location=~\"P.*\"} offset $nbDays)",
     "legendFormat": "{{location}}"
    },
    {
     "expression": "$Total - $TotalClamps - $TotalPlugs",
     "type": "math"
    }
   ]
  },
  {
   "title": "Total (${timelineTotal})",
   "type": "volkovlabs-echarts-panel",
   "description": "Energy Consumed daily (kWh)",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "(increase(sensors_teleinfo_BBRHPJB{location=\"main\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange}) offset -${timelineRange}",
     "legendFormat": "Heures Creuses"
    },
    {
     "expr": "(increase(sensors_teleinfo_BBRHCJB{location=\"main\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange}) offset -${timelineRange}",
     "legendFormat": "Heures Pleines"
    },
    {
     "expr": "(increase(sensors_teleinfo_BBRHPJW{location=\"main\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange}) offset -${timelineRange}",
     "legendFormat": "Heures Creuses"
    },
    {
     "expr": "(increase(sensors_teleinfo_BBRHCJW{location=\"main\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange}) offset -${timelineRange}",
     "legendFormat": "Heures Pleines"
    },
    {
     "expr": "(increase(sensors_teleinfo_BBRHPJR{location=\"main\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange}) offset -${timelineRange}",
     "legendFormat": "Heures Creuses"
    },
    {
     "expr": "(increase(sensors_teleinfo_BBRHCJR{location=\"main\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange}) offset -${timelineRange}",
     "legendFormat": "Heures Pleines"
    }
   ]
  },
  {
   "title": "Clamps (kWh)",
   "type": "volkovlabs-echarts-panel",
   "description": "Clamps consumption. \nThis does not take cost period into account.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "(increase(sensors_zigbee_energy_l1{location=\"C01~Garage~PowerMeter\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange}) offset -${timelineRange}",
     "legendFormat": "1-Car Charging"
    },
    {
     "expr": "(increase(sensors_zigbee_energy_l2{location=\"C01~Garage~PowerMeter\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange}) offset -${timelineRange}",
     "legendFormat": "2-Water Heater"
    },
    {
     "expr": "(increase(sensors_zigbee_energy_l3{location=\"C01~Garage~PowerMeter\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange}) offset -${timelineRange}",
     "legendFormat": "3-Heaters"
    },
    {
     "expr": "(increase(sensors_zigbee_energy{location=~\"P.*\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange}) offset -${timelineRange}",
     "legendFormat": "{{location}}"
    }
   ]
  }
 ]
}