{
 "title": "OpenDTU",
 "description": "Dashboard for OpenDTU",
 "tags": [ "solar" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "serial",
    "query": {
     "query": "label_values(opendtu_last_update,serial)"
    }
   },
   {
    "name": "channel",
    "query": {
     "query": "label_values(opendtu_PanelInfo,channel)"
    }
   },
   { "name": "bar_chart_interval", "label": "Bar Chart Interval", "query": "15m,30m,1h,2h" },
   { "name": "bar_chart_duration", "label": "Bar Chart Duration", "query": "7d,30d,90d,180d,365d" },
   { "name": "cent", "label": "Cent / kWh", "query": "25" },
   {
    "name": "solar_cost",
    "label": "Costs of installed Solar System",
    "query": "500"
   }
  ]
 },
 "panels": [
  {
   "title": "OpenDTU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "OpenDTU Build",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "opendtu_build{}", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Platform Arch",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "opendtu_platform{}", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Heap",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "opendtu_free_heap_size{}", "legendFormat": "__auto" },
      { "expr": "opendtu_heap_size{}", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "WiFi RSSI",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 14, "x": 10, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      { "expr": "wifi_rssi{}", "legendFormat": "rssi" }
     ]
    },
    {
     "title": "OpenDTU ID",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "opendtu_build{}", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "OpenDTU Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "opendtu_build{}", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Platform MAC",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "opendtu_platform{}", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "OpenDTU Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "opendtu_uptime{}", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "WiFi BSSID",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "wifi_station{}", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Last Update",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      { "expression": "$uptime-$last_update", "type": "math" }
     ]
    }
   ]
  },
  { "title": "Inverter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_last_update{serial=\"$serial\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$uptime-$last_update", "type": "math" }
   ]
  },
  {
   "title": "Production (Total - AC)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_YieldTotal{serial=\"$serial\", type=\"AC\"}",
     "legendFormat": "Solar"
    },
    {
     "expr": "sensors_zigbee_energy_produced_b{location=\"C03~Garage~PowerMeter\"}",
     "legendFormat": "ToGrid"
    }
   ]
  },
  {
   "title": "Power now",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "opendtu_Power{serial=\"$serial\", type=\"AC\"}[5m]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Production (Today - AC)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "opendtu_YieldDay{serial=\"$serial\", type=\"AC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Highest Power Peak (AC)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(opendtu_Power{serial=\"$serial\", type=\"AC\"}[$__range])",
     "legendFormat": "P-{{type}}"
    }
   ]
  },
  {
   "title": "RoI",
   "type": "stat",
   "description": "Total cost: $solar_cost€",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max_over_time(opendtu_YieldDay{serial=\"$serial\", type=\"AC\"}[1d]) / 1000 * $cent / 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "opendtu_YieldTotal{serial=\"$serial\", type=\"AC\"} * $cent / 100",
     "legendFormat": "__auto"
    },
    {
     "expression": "($solar_cost - $total_savings) / $euros_per_day",
     "type": "math"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_Temperature{serial=\"$serial\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Autoconso (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "100 - (${PGrid} *  100 / ${PSolar})",
     "type": "math"
    }
   ]
  },
  {
   "title": "Highest Power Peak (DC)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(opendtu_Power{serial=\"$serial\", type=\"DC\"}[$__range])",
     "legendFormat": "P-{{type}}-{{unit}}-{{channel}}"
    },
    {
     "expr": "sum(max_over_time(opendtu_Power{serial=\"$serial\", type=\"DC\"}[$__range]))",
     "legendFormat": "P-DC-Total"
    }
   ]
  },
  {
   "title": "Yield (€) ($cent cent)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_YieldTotal{serial=\"$serial\", type=\"AC\"} * $cent / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yield (avg €/day) ($cent cent, $bar_chart_duration)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max_over_time(opendtu_YieldDay{serial=\"$serial\", type=\"AC\"}[1d]) / 1000 * $cent / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per Day (Last $bar_chart_duration)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(increase(opendtu_YieldTotal{serial=\"$serial\", type=\"AC\"}[1d] offset -1d)) or vector(0)",
     "legendFormat": "Energy"
    }
   ]
  },
  {
   "title": "365d energy production",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 19h)[365d:1d]) @end()",
     "legendFormat": "5h"
    },
    {
     "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 18h)[365d:1d]) @end()",
     "legendFormat": "6h"
    },
    {
     "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 17h)[365d:1d]) @end()",
     "legendFormat": "7h"
    },
    {
     "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 16h)[365d:1d]) @end()",
     "legendFormat": "8h"
    },
    {
     "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 15h)[365d:1d]) @end()",
     "legendFormat": "9h"
    },
    {
     "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 14h)[365d:1d]) @end()",
     "legendFormat": "10h"
    },
    {
     "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 13h)[365d:1d]) @end()",
     "legendFormat": "11h"
    },
    {
     "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 12h)[365d:1d]) @end()",
     "legendFormat": "12h"
    },
    {
     "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 11h)[365d:1d]) @end()",
     "legendFormat": "13h"
    },
    {
     "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 10h)[365d:1d]) @end()",
     "legendFormat": "14h"
    },
    {
     "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 9h)[365d:1d]) @end()",
     "legendFormat": "15h"
    },
    {
     "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 8h)[365d:1d]) @end()",
     "legendFormat": "16h"
    },
    {
     "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 7h)[365d:1d]) @end()",
     "legendFormat": "17h"
    },
    {
     "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 6h)[365d:1d]) @end()",
     "legendFormat": "18h"
    },
    {
     "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 5h)[365d:1d]) @end()",
     "legendFormat": "19h"
    },
    {
     "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 4h)[365d:1d]) @end()",
     "legendFormat": "20h"
    },
    {
     "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 3h)[365d:1d]) @end()",
     "legendFormat": "21h"
    }
   ]
  },
  { "title": "365d energy production", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 } },
  {
   "title": "Inverter 72/h",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Energy Solar /h",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "expr": "sum(increase(opendtu_YieldTotal{serial=\"$serial\", type=\"AC\"}[$bar_chart_interval] offset -$bar_chart_interval)) or vector(0)",
       "legendFormat": "Solar"
      }
     ]
    },
    {
     "title": "Energy /h (from grid)",
     "type": "barchart",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "expr": "((sum(increase(sensors_zigbee_energy_b{}[$bar_chart_interval] offset -$bar_chart_interval)) or vector(0)) - (sum(increase(sensors_zigbee_energy_produced_b{}[$bar_chart_interval] offset -$bar_chart_interval)) or vector(0))) * 1000",
       "legendFormat": "Energy /h"
      }
     ]
    }
   ]
  },
  {
   "title": "Inverter Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "opendtu_Voltage{serial=\"$serial\", type=\"AC\"}",
       "legendFormat": "AC"
      },
      {
       "expr": "opendtu_Voltage{serial=\"$serial\", type=\"DC\"}",
       "legendFormat": "DC {{channel}}"
      }
     ]
    },
    {
     "title": "Current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "opendtu_Current{serial=\"$serial\", type=\"AC\"}",
       "legendFormat": "AC Current"
      },
      {
       "expr": "opendtu_Current{serial=\"$serial\", type=\"DC\"}",
       "legendFormat": "DC {{channel}} Current"
      }
     ]
    },
    {
     "title": "Power Factor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "opendtu_PowerFactor{serial=\"$serial\"}",
       "legendFormat": "Power Factor"
      }
     ]
    },
    {
     "title": "Power",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "opendtu_Power{serial=\"$serial\", type=\"AC\"}",
       "legendFormat": "Total AC Power"
      },
      {
       "expr": "opendtu_PowerDC{serial=\"$serial\"}",
       "legendFormat": "Total DC Power"
      },
      {
       "expr": "opendtu_Power{serial=\"$serial\", type=\"DC\"}",
       "legendFormat": "{{name}}-{{channel}} DC Power"
      }
     ]
    },
    {
     "title": "Reactive Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "voltampreact" } },
     "targets": [
      {
       "expr": "opendtu_ReactivePower{serial=\"$serial\"}",
       "legendFormat": "Reactive Power"
      }
     ]
    },
    {
     "title": "Frequency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "opendtu_Frequency{serial=\"$serial\"}",
       "legendFormat": "Frequency"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "opendtu_Temperature{serial=\"$serial\"}",
       "legendFormat": "Temperature"
      }
     ]
    },
    {
     "title": "Efficiency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "opendtu_Efficiency{serial=\"$serial\"}",
       "legendFormat": "Efficiency"
      }
     ]
    },
    {
     "title": "Power Loss in W",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "opendtu_Power{serial=\"$serial\", type=\"AC\"} / opendtu_Efficiency{serial=\"$serial\"} * 100 - opendtu_Power{serial=\"$serial\", type=\"AC\"}",
       "legendFormat": "Loss"
      }
     ]
    }
   ]
  },
  {
   "title": "Channel $channel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "repeat": "channel",
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Name",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opendtu_PanelInfo{serial=\"$serial\", channel=\"$channel\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Panel Max Power",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 5, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opendtu_MaxPower{serial=\"$serial\", channel=\"$channel\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Power Channel $channel",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opendtu_Power{serial=\"$serial\", type=\"DC\", channel=\"$channel\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Production Channel $channel (Today)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opendtu_YieldDay{serial=\"$serial\", type=\"DC\", channel=\"$channel\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Production Channel $channel (Total)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opendtu_YieldTotal{serial=\"$serial\", type=\"DC\", channel=\"$channel\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Irradiation Channel $channel",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opendtu_Irradiation{serial=\"$serial\", type=\"DC\", channel=\"$channel\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Channel Voltage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "opendtu_Voltage{serial=\"$serial\", channel=\"$channel\", type=\"DC\"}",
       "legendFormat": "Channel {{channel}} DC Voltage"
      }
     ]
    },
    {
     "title": "Current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "opendtu_Current{serial=\"$serial\", type=\"DC\", channel=\"$channel\"}",
       "legendFormat": "Channel {{channel}} DC Current"
      }
     ]
    },
    {
     "title": "Irradiation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "opendtu_Irradiation{serial=\"$serial\", type=\"DC\", channel=\"$channel\"}",
       "legendFormat": "Channel {{channel}} Irradiation"
      }
     ]
    },
    {
     "title": "Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "opendtu_Power{serial=\"$serial\", channel=\"$channel\", type=\"DC\"}",
       "legendFormat": "Total DC Power"
      },
      {
       "expr": "opendtu_MaxPower{serial=\"$serial\", channel=\"$channel\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}