{
 "title": "Tidhome - Power",
 "description": "Power Consumption Graphs",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "kWhBase", "label": "kWhHP", "query": "0.2016" },
   { "name": "kWhHP", "label": "kWhHP", "query": "0.2146" },
   { "name": "kWhHC", "label": "kWhHC", "query": "0.1696" },
   { "name": "kWhTBHC", "label": "kWhTBHC", "query": "0.1288" },
   { "name": "kWhTBHP", "label": "kWhTBH9", "query": "0.1552" },
   { "name": "kWhTWHC", "label": "kWhTWHC", "query": "0.1447" },
   { "name": "kWhTWHP", "label": "kWhTWHP", "query": "0.1792" },
   { "name": "kWhTRHC", "label": "kWhTRHC", "query": "0.1518" },
   { "name": "kWhTRHP", "label": "kWhTRHP", "query": "0.6586" },
   { "name": "kWhZenFix", "query": "0.1753" },
   { "name": "kWhZenFixHC", "query": "0.1608" },
   { "name": "kWhZenFixHP", "query": "0.2028" },
   { "name": "day1", "label": "1 Day", "query": "1d" },
   { "name": "day7", "label": "7 Day", "query": "7d" },
   { "name": "day30", "label": "30 Day", "query": "30d" },
   { "name": "day60", "label": "60 Day", "query": "60d" },
   { "name": "day365", "label": "365 Day", "query": "365d" },
   { "name": "nbDays", "label": "Days in Donut", "query": "365d" },
   { "name": "donutValueAs", "label": "Donut Value As", "query": "percent,kWh,€" },
   { "name": "timelineRange", "label": "Timeline Range", "query": "1h,1d,1w,30d" },
   { "name": "timelineTotal", "label": "Timeline Total", "query": "kWh,tempo,blue,base" },
   {
    "name": "hour",
    "label": "hour",
    "query": "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23"
   }
  ]
 },
 "panels": [
  { "title": "Energy Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Periode",
   "type": "stat",
   "description": "High/Low power cost period",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensors_teleinfo_PTEC_int @now()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total (W - clamp)",
   "type": "gauge",
   "description": "Current Total Power consumption",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensors_zigbee_power_b{location=\"C03~Garage~PowerMeter\"} @ now()",
     "legendFormat": "Total (clamp)"
    }
   ]
  },
  {
   "title": "$nbDays days (kWh)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$TotalHC + $TotalHP", "type": "math" },
    { "expression": "$TotalHC + $TotalHP + $RSolar", "type": "math" },
    { "expression": "$RSolar + 0", "type": "math" },
    { "expression": "$TotalProduced + 0", "type": "math" }
   ]
  },
  {
   "title": "Consumers (W)",
   "type": "gauge",
   "description": "Largest consumers: Car, Water heating, Electric heating",
   "gridPos": { "h": 12, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensors_zigbee_power_l1{location=\"C01~Garage~PowerMeter\"} @ now()",
     "legendFormat": "Car"
    },
    {
     "expr": "sensors_zigbee_power_l2{location=\"C01~Garage~PowerMeter\"} @ now()",
     "legendFormat": "Water"
    },
    {
     "expr": "sensors_zigbee_power_l3{location=\"C01~Garage~PowerMeter\"} @ now()",
     "legendFormat": "Heaters"
    }
   ]
  },
  {
   "title": "Outlets (W)",
   "type": "gauge",
   "description": "Current Power on outlets",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensors_zigbee_power{location=~\"P.+\"} @ now()",
     "legendFormat": "{{location}}"
    },
    {
     "expr": "sensors_zigbee_power_l1{location=\"C02~Garage~PowerMeter\"} @ now()",
     "legendFormat": "Box/NAS"
    },
    {
     "expr": "sensors_zigbee_power_l2{location=\"C02~Garage~PowerMeter\"} @ now()",
     "legendFormat": "TBD2"
    },
    {
     "expr": "sensors_zigbee_power_l3{location=\"C02~Garage~PowerMeter\"} @ now()",
     "legendFormat": "TBD3"
    }
   ]
  },
  {
   "title": "Cost (€) - Tempo",
   "type": "stat",
   "description": "Costs computed with Low/High hours energy prices",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Eu" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @end() offset $day1)) / 1000) * $kWhTBHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end() - (sensors_teleinfo_BBRHPJB{} @end() offset $day1)) / 1000) * $kWhTBHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @end() offset $day1)) / 1000) * $kWhTWHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end() - (sensors_teleinfo_BBRHPJW{} @end() offset $day1)) / 1000) * $kWhTWHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @end() offset $day1)) / 1000) * $kWhTRHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end() - (sensors_teleinfo_BBRHPJR{} @end() offset $day1)) / 1000) * $kWhTRHP))",
     "legendFormat": "$day1"
    },
    {
     "expr": "(  increase(sensors_teleinfo_BBRHCJB{}[30d]) * $kWhTBHC\n    + increase(sensors_teleinfo_BBRHPJB{}[30d]) * $kWhTBHP\n    + increase(sensors_teleinfo_BBRHCJW{}[30d]) * $kWhTWHC\n    + increase(sensors_teleinfo_BBRHPJW{}[30d]) * $kWhTWHP\n    + increase(sensors_teleinfo_BBRHCJR{}[30d]) * $kWhTRHC\n    + increase(sensors_teleinfo_BBRHPJR{}[30d]) * $kWhTRHP) / 1000",
     "legendFormat": "$day30"
    },
    {
     "expr": "(  increase(sensors_teleinfo_BBRHCJB{}[365d]) * $kWhTBHC\n    + increase(sensors_teleinfo_BBRHPJB{}[365d]) * $kWhTBHP\n    + increase(sensors_teleinfo_BBRHCJW{}[365d]) * $kWhTWHC\n    + increase(sensors_teleinfo_BBRHPJW{}[365d]) * $kWhTWHP\n    + increase(sensors_teleinfo_BBRHCJR{}[365d]) * $kWhTRHC\n    + increase(sensors_teleinfo_BBRHPJR{}[365d]) * $kWhTRHP) / 1000",
     "legendFormat": "$day365"
    },
    {
     "expr": "avg((((sensors_teleinfo_BBRHCJB{} @ 1735689600 - (sensors_teleinfo_BBRHCJB{} @ 1704067200)) / 1000) * $kWhTBHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @ 1735689600 - (sensors_teleinfo_BBRHPJB{} @ 1704067200)) / 1000) * $kWhTBHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @ 1735689600 - (sensors_teleinfo_BBRHCJW{} @ 1704067200)) / 1000) * $kWhTWHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @ 1735689600 - (sensors_teleinfo_BBRHPJW{} @ 1704067200)) / 1000) * $kWhTWHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @ 1735689600 - (sensors_teleinfo_BBRHCJR{} @ 1704067200)) / 1000) * $kWhTRHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @ 1735689600 - (sensors_teleinfo_BBRHPJR{} @ 1704067200)) / 1000) * $kWhTRHP))",
     "legendFormat": "2024"
    },
    {
     "expr": "avg((((sensors_teleinfo_BBRHCJB{} @ 1767225600 - (sensors_teleinfo_BBRHCJB{} @ 1735689600)) / 1000) * $kWhTBHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @ 1767225600 - (sensors_teleinfo_BBRHPJB{} @ 1735689600)) / 1000) * $kWhTBHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @ 1767225600 - (sensors_teleinfo_BBRHCJW{} @ 1735689600)) / 1000) * $kWhTWHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @ 1767225600 - (sensors_teleinfo_BBRHPJW{} @ 1735689600)) / 1000) * $kWhTWHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @ 1767225600 - (sensors_teleinfo_BBRHCJR{} @ 1735689600)) / 1000) * $kWhTRHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @ 1767225600 - (sensors_teleinfo_BBRHPJR{} @ 1735689600)) / 1000) * $kWhTRHP))",
     "legendFormat": "2025"
    },
    {
     "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @ 1767225600)) / 1000) * $kWhTBHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end() - (sensors_teleinfo_BBRHPJB{} @ 1767225600)) / 1000) * $kWhTBHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @ 1767225600)) / 1000) * $kWhTWHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end() - (sensors_teleinfo_BBRHPJW{} @ 1767225600)) / 1000) * $kWhTWHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @ 1767225600)) / 1000) * $kWhTRHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end() - (sensors_teleinfo_BBRHPJR{} @ 1767225600)) / 1000) * $kWhTRHP))",
     "legendFormat": "2026"
    }
   ]
  },
  {
   "title": "Total (VA - teleinfo)",
   "type": "gauge",
   "description": "Current Total Power consumption",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sensors_teleinfo_PAPP @ now()", "legendFormat": "Total (teleinfo)" }
   ]
  },
  {
   "title": "$nbDays days ($donutValueAs)",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 19, "w": 9, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum((sensors_zigbee_energy_produced_b{location=\"C03~Garage~PowerMeter\"}[1d] @end()) - (sensors_zigbee_energy_produced_b{location=\"C03~Garage~PowerMeter\"}[1d] @end() offset $nbDays))",
     "legendFormat": "TotalProduced"
    },
    {
     "expr": "sum((opendtu_YieldTotal{type=\"AC\"}[1d] @end()) - (opendtu_YieldTotal{type=\"AC\"}[1d] @end() offset $nbDays))",
     "legendFormat": "TotalSolar"
    },
    { "expression": "$TotalSolar - $TotalProduced", "type": "math" },
    {
     "expr": "(sensors_teleinfo_BBRHPJB{db=\"sensors\",location=\"main\"}[1h] - sensors_teleinfo_BBRHPJB{db=\"sensors\",location=\"main\"}[1h] offset $nbDays) / 1000",
     "legendFormat": "HPJB"
    },
    {
     "expr": "(sensors_teleinfo_BBRHPJW{db=\"sensors\",location=\"main\"}[1h] - sensors_teleinfo_BBRHPJW{db=\"sensors\",location=\"main\"}[1h] offset $nbDays) / 1000",
     "legendFormat": "HPJW"
    },
    {
     "expr": "(sensors_teleinfo_BBRHPJR{db=\"sensors\",location=\"main\"}[1h] - sensors_teleinfo_BBRHPJR{db=\"sensors\",location=\"main\"}[1h] offset $nbDays) / 1000",
     "legendFormat": "HPJR"
    },
    { "expression": "$HPJB + $HPJW + $HPJR", "type": "math" },
    {
     "expr": "(sensors_teleinfo_BBRHCJB{db=\"sensors\",location=\"main\"}[1h] - sensors_teleinfo_BBRHCJB{db=\"sensors\",location=\"main\"}[1h] offset $nbDays) / 1000",
     "legendFormat": "HCJB"
    },
    {
     "expr": "(sensors_teleinfo_BBRHCJW{db=\"sensors\",location=\"main\"}[1h] - sensors_teleinfo_BBRHCJW{db=\"sensors\",location=\"main\"}[1h] offset $nbDays) / 1000",
     "legendFormat": "HCJW"
    },
    {
     "expr": "(sensors_teleinfo_BBRHCJR{db=\"sensors\",location=\"main\"}[1h] - sensors_teleinfo_BBRHCJR{db=\"sensors\",location=\"main\"}[1h] offset $nbDays) / 1000",
     "legendFormat": "HCJR"
    },
    { "expression": "$HCJB + $HCJW + $HCJR", "type": "math" },
    {
     "expr": "avg(sensors_zigbee_energy_l1{location=\"C01~Garage~PowerMeter\"} - (sensors_zigbee_energy_l1{location=\"C01~Garage~PowerMeter\"} offset $nbDays))",
     "legendFormat": "Car"
    },
    {
     "expr": "avg(sensors_zigbee_energy_l2{location=\"C01~Garage~PowerMeter\"} - (sensors_zigbee_energy_l2{location=\"C01~Garage~PowerMeter\"} offset $nbDays))",
     "legendFormat": "Water"
    },
    {
     "expr": "avg(sensors_zigbee_energy_l3{location=\"C01~Garage~PowerMeter\"} - (sensors_zigbee_energy_l3{location=\"C01~Garage~PowerMeter\"} offset $nbDays))",
     "legendFormat": "Heaters"
    },
    {
     "expr": "avg(sensors_zigbee_energy_l1{location=\"C02~Garage~PowerMeter\"} - (sensors_zigbee_energy_l1{location=\"C02~Garage~PowerMeter\"} offset $nbDays))",
     "legendFormat": "Box/NAS"
    },
    {
     "expr": "increase(sensors_zigbee_energy{location=~\"P.*\"}[${nbDays}])",
     "legendFormat": "{{location}}"
    },
    {
     "expression": "$TotalHP + $TotalHC +$Solar - $TotalClamps - $TotalPlugs",
     "type": "math"
    }
   ]
  },
  {
   "title": "Energy /h",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 17, "w": 15, "x": 9, "y": 13 },
   "targets": [
    {
     "expr": "(increase(sensors_zigbee_energy_l1{location=\"C01~Garage~PowerMeter\",db=\"sensors\"}[1h]) offset -1h)",
     "legendFormat": "1-Car"
    },
    {
     "expr": "(increase(sensors_zigbee_energy_l2{location=\"C01~Garage~PowerMeter\",db=\"sensors\"}[1h]) offset -1h)",
     "legendFormat": "2-WaterHeater"
    },
    {
     "expr": "(increase(sensors_zigbee_energy_l3{location=\"C01~Garage~PowerMeter\",db=\"sensors\"}[1h]) offset -1h)",
     "legendFormat": "3-Heaters"
    },
    {
     "expr": "(increase(sensors_zigbee_energy{location=~\"P.*\",db=\"sensors\"}[1h]) offset -1h) ",
     "legendFormat": "{{location}}"
    },
    {
     "expr": "(increase(sensors_zigbee_energy_produced_b{location=\"C03~Garage~PowerMeter\"}[1h]) offset -1h) ",
     "legendFormat": "ToGrid"
    },
    {
     "expr": "((increase(sensors_teleinfo_BBRHPJB{location=\"main\",db=\"sensors\"}[1h]) offset -1h)  / 1000)",
     "legendFormat": "Teleinfo-BBRHPJB"
    },
    {
     "expr": "((increase(sensors_teleinfo_BBRHCJB{location=\"main\",db=\"sensors\"}[1h]) offset -1h)  / 1000)",
     "legendFormat": "Teleinfo-BBRHCJB"
    },
    {
     "expr": "((increase(sensors_teleinfo_BBRHPJW{location=\"main\",db=\"sensors\"}[1h]) offset -1h)  / 1000)",
     "legendFormat": "Teleinfo-BBRHPJW"
    },
    {
     "expr": "((increase(sensors_teleinfo_BBRHCJW{location=\"main\",db=\"sensors\"}[1h]) offset -1h)  / 1000)",
     "legendFormat": "Teleinfo-BBRHCJW"
    },
    {
     "expr": "((increase(sensors_teleinfo_BBRHPJR{location=\"main\",db=\"sensors\"}[1h]) offset -1h)  / 1000)",
     "legendFormat": "Teleinfo-BBRHPJR"
    },
    {
     "expr": "((increase(sensors_teleinfo_BBRHCJR{location=\"main\",db=\"sensors\"}[1h]) offset -1h)  / 1000)",
     "legendFormat": "Teleinfo-BBRHCJR"
    },
    {
     "expr": "(\n  (sum(increase(opendtu_YieldTotal{type=\"AC\"}[1h]) offset -1h)) \n  - \n  (sum(increase(sensors_zigbee_energy_produced_b{location=\"C03~Garage~PowerMeter\"}[1h]) offset -1h))\n)",
     "legendFormat": "AutoConso"
    }
   ]
  },
  {
   "title": "Energy / $timelineRange",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "(increase(sensors_zigbee_energy_l1{location=\"C01~Garage~PowerMeter\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange}) offset -${timelineRange}",
     "legendFormat": "1-Car"
    },
    {
     "expr": "(increase(sensors_zigbee_energy_l2{location=\"C01~Garage~PowerMeter\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange}) offset -${timelineRange}",
     "legendFormat": "2-WaterHeater"
    },
    {
     "expr": "(increase(sensors_zigbee_energy_l3{location=\"C01~Garage~PowerMeter\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange}) offset -${timelineRange}",
     "legendFormat": "3-Heaters"
    },
    {
     "expr": "(increase(sensors_zigbee_energy{location=~\"P.*\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange}) offset -${timelineRange}",
     "legendFormat": "{{location}}"
    },
    {
     "expr": "(increase(sensors_zigbee_energy_produced_b{location=\"C03~Garage~PowerMeter\"}[${timelineRange}]) offset -${timelineRange}) offset -${timelineRange}",
     "legendFormat": "ToGrid"
    },
    {
     "expr": "((increase(sensors_teleinfo_BBRHPJB{location=\"main\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange})  / 1000) offset -${timelineRange}",
     "legendFormat": "Teleinfo-BBRHPJB"
    },
    {
     "expr": "((increase(sensors_teleinfo_BBRHCJB{location=\"main\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange})  / 1000) offset -${timelineRange}",
     "legendFormat": "Teleinfo-BBRHCJB"
    },
    {
     "expr": "((increase(sensors_teleinfo_BBRHPJW{location=\"main\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange})  / 1000) offset -${timelineRange}",
     "legendFormat": "Teleinfo-BBRHPJW"
    },
    {
     "expr": "((increase(sensors_teleinfo_BBRHCJW{location=\"main\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange})  / 1000) offset -${timelineRange}",
     "legendFormat": "Teleinfo-BBRHCJW"
    },
    {
     "expr": "((increase(sensors_teleinfo_BBRHPJR{location=\"main\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange})  / 1000) offset -${timelineRange}",
     "legendFormat": "Teleinfo-BBRHPJR"
    },
    {
     "expr": "((increase(sensors_teleinfo_BBRHCJR{location=\"main\",db=\"sensors\"}[${timelineRange}]) offset -${timelineRange})  / 1000) offset -${timelineRange}",
     "legendFormat": "Teleinfo-BBRHCJR"
    },
    {
     "expr": "(\n  (sum(increase(opendtu_YieldTotal{type=\"AC\"}[${timelineRange}]) offset -${timelineRange}) offset -${timelineRange}) \n  - \n  (sum(increase(sensors_zigbee_energy_produced_b{location=\"C03~Garage~PowerMeter\"}[${timelineRange}]) offset -${timelineRange}) offset -${timelineRange})\n)",
     "legendFormat": "AutoConso"
    }
   ]
  },
  {
   "title": "Power Timeline (W)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clamps (W)",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg_over_time(sensors_teleinfo_PAPP{}[5m])",
       "legendFormat": "Total"
      },
      {
       "expr": "avg_over_time(sensors_zigbee_power_l1{location=\"C01~Garage~PowerMeter\"}[5m])",
       "legendFormat": "1-Car Charging"
      },
      {
       "expr": "avg_over_time(sensors_zigbee_power_l2{location=\"C01~Garage~PowerMeter\"}[5m])",
       "legendFormat": "2-Water Heater"
      },
      {
       "expr": "avg_over_time(sensors_zigbee_power_l3{location=\"C01~Garage~PowerMeter\"}[5m])",
       "legendFormat": "3-Heaters"
      },
      {
       "expr": "avg_over_time(sensors_zigbee_power_l2{location=\"C02~Garage~PowerMeter\"}[5m])",
       "legendFormat": "4-VMC"
      },
      {
       "expr": "avg_over_time(sensors_zigbee_power{location=\"C01~Garage~PowerMeter\"}[5m])",
       "legendFormat": "Car+Water+Heating"
      },
      { "expr": "sensors_teleinfo_PAPP{}", "legendFormat": "Teleinfo (raw)" }
     ]
    },
    {
     "title": "Outlets (W)",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sensors_zigbee_power{location=~\"P.+\"}[1m]",
       "legendFormat": "{{location}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "30d @ lunch",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "expr": "increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 12h)[7d:1d]",
       "legendFormat": "SolarTotal"
      },
      {
       "expression": "$SolarTotal + $SolarProd + $Grid ",
       "type": "math"
      },
      { "expression": "$Home - $SolarTotal * 4", "type": "math" }
     ]
    },
    {
     "title": "365d energy production",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 19h)[365d:1d]) @end()",
       "legendFormat": "5h"
      },
      {
       "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 18h)[365d:1d]) @end()",
       "legendFormat": "6h"
      },
      {
       "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 17h)[365d:1d]) @end()",
       "legendFormat": "7h"
      },
      {
       "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 16h)[365d:1d]) @end()",
       "legendFormat": "8h"
      },
      {
       "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 15h)[365d:1d]) @end()",
       "legendFormat": "9h"
      },
      {
       "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 14h)[365d:1d]) @end()",
       "legendFormat": "10h"
      },
      {
       "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 13h)[365d:1d]) @end()",
       "legendFormat": "11h"
      },
      {
       "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 12h)[365d:1d]) @end()",
       "legendFormat": "12h"
      },
      {
       "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 11h)[365d:1d]) @end()",
       "legendFormat": "13h"
      },
      {
       "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 10h)[365d:1d]) @end()",
       "legendFormat": "14h"
      },
      {
       "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 9h)[365d:1d]) @end()",
       "legendFormat": "15h"
      },
      {
       "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 8h)[365d:1d]) @end()",
       "legendFormat": "16h"
      },
      {
       "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 7h)[365d:1d]) @end()",
       "legendFormat": "17h"
      },
      {
       "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 6h)[365d:1d]) @end()",
       "legendFormat": "18h"
      },
      {
       "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 5h)[365d:1d]) @end()",
       "legendFormat": "19h"
      },
      {
       "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 4h)[365d:1d]) @end()",
       "legendFormat": "20h"
      },
      {
       "expr": "sum_over_time(increase(opendtu_YieldTotal{type=\"AC\"}[1h] offset 3h)[365d:1d]) @end()",
       "legendFormat": "21h"
      }
     ]
    },
    {
     "title": "Cost (€) - Base",
     "type": "stat",
     "description": "Costs computed with Low/High hours energy prices",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "Eu" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @end() offset $day1)) / 1000) * $kWhBase)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_BBRHPJB{} @end() offset $day1)) / 1000) * $kWhBase))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @end() offset $day1)) / 1000) * $kWhBase)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @end() offset $day1)) / 1000) * $kWhBase))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @end() offset $day1)) / 1000) * $kWhBase)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @end() offset $day1)) / 1000) * $kWhBase))",
       "legendFormat": "$day1"
      },
      {
       "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @end() offset $day30)) / 1000) * $kWhBase)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_BBRHPJB{} @end() offset $day30)) / 1000) * $kWhBase))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @end() offset $day30)) / 1000) * $kWhBase)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @end() offset $day30)) / 1000) * $kWhBase))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @end() offset $day30)) / 1000) * $kWhBase)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @end() offset $day30)) / 1000) * $kWhBase))",
       "legendFormat": "$day30"
      },
      {
       "expr": "(     increase(sensors_teleinfo_BBRHCJB{}[365d])\n    + increase(sensors_teleinfo_BBRHPJB{}[365d])\n    + increase(sensors_teleinfo_BBRHCJW{}[365d])\n    + increase(sensors_teleinfo_BBRHPJW{}[365d])\n    + increase(sensors_teleinfo_BBRHCJR{}[365d])\n    + increase(sensors_teleinfo_BBRHPJR{}[365d])) * $kWhBase / 1000",
       "legendFormat": "$day365"
      },
      {
       "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @ 1672552800)) / 1000) * $kWhBase)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_BBRHPJB{} @ 1672552800)) / 1000) * $kWhBase))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @ 1672552800)) / 1000) * $kWhBase)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @ 1672552800)) / 1000) * $kWhBase))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @ 1672552800)) / 1000) * $kWhBase)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @ 1672552800)) / 1000) * $kWhBase))",
       "legendFormat": "2023"
      },
      {
       "expr": "avg((((sensors_teleinfo_BBRHCJB{} @ 1735689600 - (sensors_teleinfo_BBRHCJB{} @ 1704067200)) / 1000) * $kWhBase)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @ 1735689600- (sensors_teleinfo_BBRHPJB{} @ 1704067200)) / 1000) * $kWhBase))\n+\navg((((sensors_teleinfo_BBRHCJW{} @ 1735689600 - (sensors_teleinfo_BBRHCJW{} @ 1704067200)) / 1000) * $kWhBase)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @ 1735689600 - (sensors_teleinfo_BBRHPJW{} @ 1704067200)) / 1000) * $kWhBase))\n+\navg((((sensors_teleinfo_BBRHCJR{} @ 1735689600 - (sensors_teleinfo_BBRHCJR{} @ 1704067200)) / 1000) * $kWhBase)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @ 1735689600 - (sensors_teleinfo_BBRHPJR{} @ 1704067200)) / 1000) * $kWhBase))",
       "legendFormat": "2024"
      }
     ]
    },
    {
     "title": "Cost (€) - HC/HP",
     "type": "stat",
     "description": "Costs computed with Low/High hours energy prices",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "Eu" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @end() offset $day1)) / 1000) * $kWhHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_BBRHPJB{} @end() offset $day1)) / 1000) * $kWhHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @end() offset $day1)) / 1000) * $kWhHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @end() offset $day1)) / 1000) * $kWhHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @end() offset $day1)) / 1000) * $kWhHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @end() offset $day1)) / 1000) * $kWhHP))",
       "legendFormat": "$day1"
      },
      {
       "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @end() offset $day30)) / 1000) * $kWhHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_BBRHPJB{} @end() offset $day30)) / 1000) * $kWhHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @end() offset $day30)) / 1000) * $kWhHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @end() offset $day30)) / 1000) * $kWhHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @end() offset $day30)) / 1000) * $kWhHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @end() offset $day30)) / 1000) * $kWhHP))",
       "legendFormat": "$day30"
      },
      {
       "expr": "((  increase(sensors_teleinfo_BBRHCJB{}[365d])\n    + increase(sensors_teleinfo_BBRHCJW{}[365d])\n    + increase(sensors_teleinfo_BBRHCJR{}[365d])) * $kWhHC\n    +\n   (  increase(sensors_teleinfo_BBRHPJW{}[365d])\n    + increase(sensors_teleinfo_BBRHPJB{}[365d])    \n    + increase(sensors_teleinfo_BBRHPJR{}[365d])) * $kWhHP) / 1000",
       "legendFormat": "$day365"
      },
      {
       "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @ 1672552800)) / 1000) * $kWhHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_BBRHPJB{} @ 1672552800)) / 1000) * $kWhHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @ 1672552800)) / 1000) * $kWhHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @ 1672552800)) / 1000) * $kWhHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @ 1672552800)) / 1000) * $kWhHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @ 1672552800)) / 1000) * $kWhHP))",
       "legendFormat": "2023"
      },
      {
       "expr": "avg((((sensors_teleinfo_BBRHCJB{} @ 1735689600 - (sensors_teleinfo_BBRHCJB{} @ 1704067200)) / 1000) * $kWhHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @ 1735689600 - (sensors_teleinfo_BBRHPJB{} @ 1704067200)) / 1000) * $kWhHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @ 1735689600 - (sensors_teleinfo_BBRHCJW{} @ 1704067200)) / 1000) * $kWhHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @ 1735689600 - (sensors_teleinfo_BBRHPJW{} @ 1704067200)) / 1000) * $kWhHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @ 1735689600 - (sensors_teleinfo_BBRHCJR{} @ 1704067200)) / 1000) * $kWhHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @ 1735689600 - (sensors_teleinfo_BBRHPJR{} @ 1704067200)) / 1000) * $kWhHP))",
       "legendFormat": "2024"
      }
     ]
    },
    {
     "title": "Range values ($nbDays)",
     "type": "stat",
     "gridPos": { "h": 16, "w": 11, "x": 8, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(sensors_zigbee_energy_l1{location=\"C01~Garage~PowerMeter\"} - (sensors_zigbee_energy_l1{location=\"C01~Garage~PowerMeter\"} offset $nbDays))",
       "legendFormat": "Car"
      },
      {
       "expr": "avg(sensors_zigbee_energy_l2{location=\"C01~Garage~PowerMeter\"} - (sensors_zigbee_energy_l2{location=\"C01~Garage~PowerMeter\"} offset $nbDays))",
       "legendFormat": "Water"
      },
      {
       "expr": "avg(sensors_zigbee_energy_l3{location=\"C01~Garage~PowerMeter\"} - (sensors_zigbee_energy_l3{location=\"C01~Garage~PowerMeter\"} offset $nbDays))",
       "legendFormat": "Heaters"
      },
      {
       "expr": "sensors_zigbee_energy{location=~\"P.*\"} - (sensors_zigbee_energy{location=~\"P.*\"} offset $nbDays)",
       "legendFormat": "{{location}}"
      },
      {
       "expr": "avg(sensors_zigbee_energy{location=\"C01~Garage~PowerMeter\"} - (sensors_zigbee_energy{location=\"C01~Garage~PowerMeter\"} offset $nbDays))",
       "legendFormat": "TotalClamps"
      },
      {
       "expr": "sum(sensors_zigbee_energy{location=~\"P.*\"} - (sensors_zigbee_energy{location=~\"P.*\"} offset $nbDays))",
       "legendFormat": "TotalPlugs"
      },
      {
       "expression": "$Total - $TotalClamps - $TotalPlugs",
       "type": "math"
      }
     ]
    },
    {
     "title": "Range values ($nbDays)",
     "type": "stat",
     "gridPos": { "h": 16, "w": 5, "x": 19, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sensors_teleinfo_BBRHPJB{db=\"sensors\",location=\"main\"} - sensors_teleinfo_BBRHPJB{db=\"sensors\",location=\"main\"} offset $nbDays) / 1000",
       "legendFormat": "HPJB"
      },
      {
       "expr": "(sensors_teleinfo_BBRHPJW{db=\"sensors\",location=\"main\"} - sensors_teleinfo_BBRHPJW{db=\"sensors\",location=\"main\"} offset $nbDays) / 1000",
       "legendFormat": "HPJW"
      },
      {
       "expr": "(sensors_teleinfo_BBRHPJR{db=\"sensors\",location=\"main\"} - sensors_teleinfo_BBRHPJR{db=\"sensors\",location=\"main\"} offset $nbDays) / 1000",
       "legendFormat": "HPJR"
      },
      { "expression": "$HPJB + $HPJW + $HPJR", "type": "math" },
      {
       "expr": "(sensors_teleinfo_BBRHCJB{db=\"sensors\",location=\"main\"} - sensors_teleinfo_BBRHCJB{db=\"sensors\",location=\"main\"} offset $nbDays) / 1000",
       "legendFormat": "HCJB"
      },
      {
       "expr": "(sensors_teleinfo_BBRHCJW{db=\"sensors\",location=\"main\"} - sensors_teleinfo_BBRHCJW{db=\"sensors\",location=\"main\"} offset $nbDays) / 1000",
       "legendFormat": "HCJW"
      },
      {
       "expr": "(sensors_teleinfo_BBRHCJR{db=\"sensors\",location=\"main\"} - sensors_teleinfo_BBRHCJR{db=\"sensors\",location=\"main\"} offset $nbDays) / 1000",
       "legendFormat": "HCJR"
      },
      { "expression": "$HCJB + $HCJW + $HCJR", "type": "math" }
     ]
    },
    {
     "title": "Cost (€) - ZenFix",
     "type": "stat",
     "description": "Costs computed with Low/High hours energy prices",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "Eu" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @end() offset $day1)) / 1000) * $kWhZenFix)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_BBRHPJB{} @end() offset $day1)) / 1000) * $kWhZenFix))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @end() offset $day1)) / 1000) * $kWhZenFix)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @end() offset $day1)) / 1000) * $kWhZenFix))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @end() offset $day1)) / 1000) * $kWhZenFix)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @end() offset $day1)) / 1000) * $kWhZenFix))",
       "legendFormat": "$day1"
      },
      {
       "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @end() offset $day30)) / 1000) * $kWhZenFix)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_BBRHPJB{} @end() offset $day30)) / 1000) * $kWhZenFix))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @end() offset $day30)) / 1000) * $kWhZenFix)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @end() offset $day30)) / 1000) * $kWhZenFix))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @end() offset $day30)) / 1000) * $kWhZenFix)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @end() offset $day30)) / 1000) * $kWhZenFix))",
       "legendFormat": "$day30"
      },
      {
       "expr": "(  increase(sensors_teleinfo_BBRHCJB{}[365d])\n    + increase(sensors_teleinfo_BBRHPJB{}[365d])\n    + increase(sensors_teleinfo_BBRHCJW{}[365d])\n    + increase(sensors_teleinfo_BBRHPJW{}[365d])\n    + increase(sensors_teleinfo_BBRHCJR{}[365d])\n    + increase(sensors_teleinfo_BBRHPJR{}[365d])) * $kWhZenFix / 1000",
       "legendFormat": "$day365"
      },
      {
       "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @ 1672552800)) / 1000) * $kWhZenFix)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_BBRHPJB{} @ 1672552800)) / 1000) * $kWhZenFix))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @ 1672552800)) / 1000) * $kWhZenFix)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @ 1672552800)) / 1000) * $kWhZenFix))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @ 1672552800)) / 1000) * $kWhZenFix)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @ 1672552800)) / 1000) * $kWhZenFix))",
       "legendFormat": "2023"
      },
      {
       "expr": "avg((((sensors_teleinfo_BBRHCJB{} @ 1735689600 - (sensors_teleinfo_BBRHCJB{} @ 1704067200)) / 1000) * $kWhZenFix)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @ 1735689600 - (sensors_teleinfo_BBRHPJB{} @ 1704067200)) / 1000) * $kWhZenFix))\n+\navg((((sensors_teleinfo_BBRHCJW{} @ 1735689600 - (sensors_teleinfo_BBRHCJW{} @ 1704067200)) / 1000) * $kWhZenFix)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @ 1735689600 - (sensors_teleinfo_BBRHPJW{} @ 1704067200)) / 1000) * $kWhZenFix))\n+\navg((((sensors_teleinfo_BBRHCJR{} @ 1735689600 - (sensors_teleinfo_BBRHCJR{} @ 1704067200)) / 1000) * $kWhZenFix)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @ 1735689600 - (sensors_teleinfo_BBRHPJR{} @ 1704067200)) / 1000) * $kWhZenFix))",
       "legendFormat": "2024"
      }
     ]
    },
    {
     "title": "Cost (€) - ZenFix HP/HC",
     "type": "stat",
     "description": "Costs computed with Low/High hours energy prices",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "Eu" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @end() offset $day1)) / 1000) * $kWhZenFixHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_BBRHPJB{} @end() offset $day1)) / 1000) * $kWhZenFixHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @end() offset $day1)) / 1000) * $kWhZenFixHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @end() offset $day1)) / 1000) * $kWhZenFixHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @end() offset $day1)) / 1000) * $kWhZenFixHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @end() offset $day1)) / 1000) * $kWhZenFixHP))",
       "legendFormat": "$day1"
      },
      {
       "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @end() offset $day30)) / 1000) * $kWhZenFixHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_BBRHPJB{} @end() offset $day30)) / 1000) * $kWhZenFixHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @end() offset $day30)) / 1000) * $kWhZenFixHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @end() offset $day30)) / 1000) * $kWhZenFixHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @end() offset $day30)) / 1000) * $kWhZenFixHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @end() offset $day30)) / 1000) * $kWhZenFixHP))",
       "legendFormat": "$day30"
      },
      {
       "expr": "((  increase(sensors_teleinfo_BBRHCJB{}[365d])\n    + increase(sensors_teleinfo_BBRHCJW{}[365d])\n    + increase(sensors_teleinfo_BBRHCJR{}[365d])) * $kWhZenFixHC\n    +\n   (  increase(sensors_teleinfo_BBRHPJW{}[365d])\n    + increase(sensors_teleinfo_BBRHPJB{}[365d])    \n    + increase(sensors_teleinfo_BBRHPJR{}[365d])) * $kWhZenFixHP) / 1000",
       "legendFormat": "$day365"
      },
      {
       "expr": "avg((((sensors_teleinfo_BBRHCJB{} @end() - (sensors_teleinfo_BBRHCJB{} @ 1672552800)) / 1000) * $kWhZenFixHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @end()- (sensors_teleinfo_BBRHPJB{} @ 1672552800)) / 1000) * $kWhZenFixHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @end() - (sensors_teleinfo_BBRHCJW{} @ 1672552800)) / 1000) * $kWhZenFixHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @end()- (sensors_teleinfo_BBRHPJW{} @ 1672552800)) / 1000) * $kWhZenFixHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @end() - (sensors_teleinfo_BBRHCJR{} @ 1672552800)) / 1000) * $kWhZenFixHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @end()- (sensors_teleinfo_BBRHPJR{} @ 1672552800)) / 1000) * $kWhZenFixHP))",
       "legendFormat": "2023"
      },
      {
       "expr": "avg((((sensors_teleinfo_BBRHCJB{} @ 1735689600 - (sensors_teleinfo_BBRHCJB{} @ 1704067200)) / 1000) * $kWhZenFixHC)) \n+\navg((((sensors_teleinfo_BBRHPJB{} @ 1735689600 - (sensors_teleinfo_BBRHPJB{} @ 1704067200)) / 1000) * $kWhZenFixHP))\n+\navg((((sensors_teleinfo_BBRHCJW{} @ 1735689600 - (sensors_teleinfo_BBRHCJW{} @ 1704067200)) / 1000) * $kWhZenFixHC)) \n+\navg((((sensors_teleinfo_BBRHPJW{} @ 1735689600 - (sensors_teleinfo_BBRHPJW{} @ 1704067200)) / 1000) * $kWhZenFixHP))\n+\navg((((sensors_teleinfo_BBRHCJR{} @ 1735689600 - (sensors_teleinfo_BBRHCJR{} @ 1704067200)) / 1000) * $kWhZenFixHC)) \n+\navg((((sensors_teleinfo_BBRHPJR{} @ 1735689600 - (sensors_teleinfo_BBRHPJR{} @ 1704067200)) / 1000) * $kWhZenFixHP))",
       "legendFormat": "2024"
      }
     ]
    }
   ]
  }
 ]
}