notifiers:
  - name: notification-channel-1
    type: telegram
    uid: notifier1
    org_id: 1
    is_default: true
    send_reminder: true
    frequency: 1h
    disable_resolve_message: false
    # See `Supported Settings` section for settings supported for each
    # alert notification type.
    settings:
      bottoken: '${TELEGRAM_TOKEN}'
      chatid: ${TELEGRAM_CHATID}
      uploadImage: true

delete_notifiers:
  - name: notification-channel-1
    uid: notifier1
    org_id: 1
