- id: 112e9cf8.590b23
  type: tab
  label: Config
  disabled: false
  info: ''
- id: f26be183.4f807
  type: inject
  z: 112e9cf8.590b23
  name: Initialize
  repeat: ''
  crontab: ''
  once: true
  onceDelay: '1'
  topic: ''
  payload: ''
  payloadType: date
  x: 100
  'y': 440
  wires:
    - - 94e381cf.c2bab
- id: af26e828.9b92
  type: debug
  z: 112e9cf8.590b23
  name: Config-Sensors-Debug
  active: false
  tosidebar: true
  console: true
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 920
  'y': 440
  wires: []
- id: 77ded097.d4bc6
  type: yaml
  z: 112e9cf8.590b23
  property: payload
  name: ''
  x: 470
  'y': 440
  wires:
    - - 87655eff.6eacc
- id: 94e381cf.c2bab
  type: file in
  z: 112e9cf8.590b23
  name: ti-dhome.yaml
  filename: /etc/tidhome/ti-dhome.yaml
  format: utf8
  chunk: false
  sendError: false
  x: 290
  'y': 440
  wires:
    - - 77ded097.d4bc6
- id: ea98f666.7ddaa
  type: comment
  z: 112e9cf8.590b23
  name: Sensors - Configuration
  info: ''
  x: 140
  'y': 400
  wires: []
- id: d4efc750.434898
  type: catch
  z: 112e9cf8.590b23
  name: ''
  scope: null
  uncaught: false
  x: 100
  'y': 80
  wires:
    - - a24eb884.8fa9a
- id: 87655eff.6eacc
  type: change
  z: 112e9cf8.590b23
  name: ''
  rules:
    - t: set
      p: tidhome
      pt: global
      to: payload
      tot: msg
      dc: true
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 630
  'y': 440
  wires:
    - - af26e828.9b92
- id: aa1dfa0a.c912b
  type: inject
  z: 112e9cf8.590b23
  name: Alarms
  props:
    - p: payload
    - p: topic
      vt: str
  repeat: '3600'
  crontab: ''
  once: true
  onceDelay: '900'
  topic: ''
  payload: '["iotpower","iotheaters","rfm868usb"]'
  payloadType: json
  x: 100
  'y': 620
  wires:
    - []
- id: 9bca5b14.acefe8
  type: function
  z: 112e9cf8.590b23
  name: Loop on sensors & alarm
  func: |-
    var outputMsgs = []
    var now = new Date().getTime()
    var nowH = new Date().toISOString()

    // Read global info
    for (var j = 0; j < msg.payload.length; j++) {
        var topicNodesPrefix = 'tidhome.sensors.' + msg.payload[j] + '.nodes'
        var nodes = global.get(topicNodesPrefix) || []
        for (var i = 0; i < nodes.length; i++) {
            
            if(nodes[i].enabled != undefined && nodes[i].enabled == false)
                continue
            
            // sensor is configured but never seen !
            if(nodes[i].timestamp == undefined) {
                if(nodes[i].notifiedAt == undefined) {
                    var msgOut = {}
                    msgOut.payload = nodes[i]
                    msgOut.payload.gateway = msg.payload[j]
                    msgOut.payload.state = 'neverseen'
                    msgOut.payload.notifiedAt = now
                    msgOut.payload.notifiedAt_human = nowH
                    outputMsgs.push(msgOut)
                    continue
                }
                
            } else {
            
                // sensor no longer seen after 60min !
                var tOld = parseInt((now - nodes[i].timestamp) / (1000 * 60))
                if(tOld > 60) {
                    if(nodes[i].notifiedAt == undefined) {
                        // 30 min old data => alarm
                        var msgOut = {}
                        msgOut.payload = nodes[i]
                        msgOut.payload.gateway = msg.payload[j]
                        msgOut.payload.state = 'unavailable'
                        msgOut.payload.notifiedAt = now
                        msgOut.payload.notifiedAt_human = nowH
                        msgOut.payload.for = tOld
                        outputMsgs.push(msgOut)
                    }
                    
                } else {
                    if(nodes[i].notifiedAt != undefined) {
                        // reset notifiedAt
                        global.set(topicNodesPrefix + '[' + i + '].notifiedAt', undefined);
                        global.set(topicNodesPrefix + '[' + i + '].notifiedAt_human', undefined);
                        global.set(topicNodesPrefix + '[' + i + '].for', undefined);
                        
                        var msgOut = {}
                        msgOut.payload = nodes[i]
                        msgOut.payload.state = 'available'
                        msgOut.payload.gateway = msg.payload[j]
                        outputMsgs.push(msgOut)
                    }
                }
                
                // sensor is reporting low battery !
                // TODO
            }
        }
    }

    // return [ outputMsgs ];

    // Factorize a single message
    var finalMessage = ""
    for (var j = 0; j < outputMsgs.length; j++) {
        amsg = outputMsgs[j]
        finalMessage += amsg.payload.state + ": " + amsg.payload.gateway + " / " + amsg.payload.location + "(" + amsg.payload.id + ")"
        if(amsg.payload.for != undefined) {
            finalMessage += amsg.payload.for + "min"
        }
        finalMessage += "\n"
    }

    msg.payload = finalMessage
    return msg;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 320
  'y': 620
  wires:
    - - ecb2912f7071e62b
- id: 650449d4.5383f8
  type: comment
  z: 112e9cf8.590b23
  name: ERRORS Handling
  info: ''
  x: 130
  'y': 40
  wires: []
- id: 29f69392.4ebc64
  type: debug
  z: 112e9cf8.590b23
  name: Config-Log-Debug
  active: false
  tosidebar: true
  console: true
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 910
  'y': 250
  wires: []
- id: 41e3caeb.c73014
  type: delay
  z: 112e9cf8.590b23
  name: ''
  pauseType: rate
  timeout: '5'
  timeoutUnits: seconds
  rate: '1'
  nbRateUnits: '30'
  rateUnits: minute
  randomFirst: '1'
  randomLast: '5'
  randomUnits: seconds
  drop: true
  outputs: 1
  x: 680
  'y': 210
  wires:
    - - 84b1892ac15ea678
- id: 2d2c7365.5aa924
  type: file
  z: 112e9cf8.590b23
  name: ''
  filename: /var/log/nodered/flow-errors.log
  appendNewline: true
  createDir: false
  overwriteFile: 'false'
  encoding: none
  x: 660
  'y': 250
  wires:
    - - 29f69392.4ebc64
- id: a24eb884.8fa9a
  type: link out
  z: 112e9cf8.590b23
  name: Config-CatchAll-Out
  mode: link
  links:
    - 1bf42829.b3e0b8
  x: 835
  'y': 80
  wires: []
- id: 1bf42829.b3e0b8
  type: link in
  z: 112e9cf8.590b23
  name: Config-CatchAll-In
  links:
    - 4a641f47.46cb08
    - 4d670d8450380ac6
    - 5d10dd0b.1db574
    - 60b06b25.f9c98c
    - 64dacb8b.d2f3e4
    - 7ddfd97.7160228
    - 950a0758.599f88
    - 98c9017f.76bca
    - a24eb884.8fa9a
    - da805bda.a8c0b
  x: 225
  'y': 240
  wires:
    - - 41e3caeb.c73014
      - 2d2c7365.5aa924
- id: efba45ee82a7b481
  type: comment
  z: 112e9cf8.590b23
  name: Sensors - Alerts
  info: ''
  x: 120
  'y': 580
  wires: []
- id: 84b1892ac15ea678
  type: link out
  z: 112e9cf8.590b23
  name: Config-CatchAll-Notif-Out
  mode: link
  links:
    - 2f30621f40aa8285
  x: 805
  'y': 210
  wires: []
- id: ecb2912f7071e62b
  type: link out
  z: 112e9cf8.590b23
  name: Config-Sensors-Alarm-Out
  mode: link
  links:
    - 2f30621f40aa8285
  x: 485
  'y': 620
  wires: []
