- id: d88a69c4.1942c8
  type: tab
  label: DB
  disabled: false
  info: ''
- id: ed8532c35449ea5d
  type: junction
  z: d88a69c4.1942c8
  x: 240
  'y': 360
  wires:
    - - 7e3ea563.cfecfc
      - 2b444ab.4ee2eb6
- id: cc675ec4.106d
  type: comment
  z: d88a69c4.1942c8
  name: Sensors - Heaters/Power/RFM868
  info: ''
  x: 180
  'y': 120
  wires: []
- id: 90d304a9.c871a
  type: mqtt in
  z: d88a69c4.1942c8
  name: sensors/#
  topic: sensors/#
  qos: '2'
  datatype: json
  broker: c38452a5.4f84e8
  inputs: 0
  x: 100
  'y': 160
  wires:
    - - dcd509f1.d56dd
- id: 14def27.355280e
  type: debug
  z: d88a69c4.1942c8
  name: Debug
  active: false
  tosidebar: true
  console: true
  tostatus: false
  complete: 'true'
  targetType: full
  x: 420
  'y': 160
  wires: []
- id: dcd509f1.d56dd
  type: function
  z: d88a69c4.1942c8
  name: Store Global
  func: |-
    var topicNodesPrefix = 'tidhome.sensors.' + msg.payload.gateway + '.nodes'
    var nodes = global.get(topicNodesPrefix) || [];
    for (var i = 0; i < nodes.length; i++) {
        if(nodes[i].id === msg.payload.id) {
            // found node
            let entryStr = (msg.payload.entry != undefined) ? ('-' + msg.payload.entry) : ''
            global.set(topicNodesPrefix + '[' + i + '].' + msg.payload.type + entryStr, msg.payload.value);
            global.set(topicNodesPrefix + '[' + i + '].timestamp', msg.payload.timestamp);
        }
    }
    // pass through
    return msg;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 260
  'y': 160
  wires:
    - - 14def27.355280e
- id: 694da039.ceca8
  type: catch
  z: d88a69c4.1942c8
  name: ''
  scope: null
  uncaught: false
  x: 100
  'y': 80
  wires:
    - - 950a0758.599f88
- id: 950a0758.599f88
  type: link out
  z: d88a69c4.1942c8
  name: General CatchAll
  links:
    - 1bf42829.b3e0b8
  x: 255
  'y': 80
  wires: []
- id: f9ad7f8e.736a08
  type: influxdb in
  z: d88a69c4.1942c8
  influxdb: 786c015f0b3c18d1
  name: ''
  query: ''
  rawOutput: false
  precision: ''
  retentionPolicy: ''
  org: organisation
  x: 730
  'y': 560
  wires:
    - - fe17bda8.2a07a8
- id: 266e0143.d568d6
  type: comment
  z: d88a69c4.1942c8
  name: Selects
  info: ''
  x: 90
  'y': 500
  wires: []
- id: fe17bda8.2a07a8
  type: debug
  z: d88a69c4.1942c8
  name: ''
  active: true
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 1030
  'y': 560
  wires: []
- id: 7ad1b802.d1df98
  type: inject
  z: d88a69c4.1942c8
  name: SELECT * FROM "sensors" WHERE "type" = 'temp' AND "value" > 22
  props:
    - p: query
      v: SELECT * FROM "sensors_ccost_PAPP" WHERE "value" > 22
      vt: str
  repeat: ''
  crontab: ''
  once: false
  onceDelay: 0.1
  topic: ''
  x: 290
  'y': 560
  wires:
    - - f9ad7f8e.736a08
- id: 716819cb.d00088
  type: comment
  z: d88a69c4.1942c8
  name: insert - events
  info: ''
  x: 110
  'y': 300
  wires: []
- id: ea4448b9.c62a4
  type: inject
  z: d88a69c4.1942c8
  name: SELECT * FROM "one_month"."downsampled_sensors"
  props:
    - p: query
      v: SELECT * FROM "one_month"."downsampled_sensors"
      vt: str
  repeat: ''
  crontab: ''
  once: false
  onceDelay: 0.1
  topic: ''
  x: 240
  'y': 600
  wires:
    - - f9ad7f8e.736a08
- id: bf874566.5d9478
  type: influxdb out
  z: d88a69c4.1942c8
  influxdb: ab73d852ece55e2a
  name: ''
  measurement: ''
  precision: ''
  retentionPolicy: ''
  database: ''
  retentionPolicyV18Flux: ''
  org: ''
  bucket: ''
  x: 540
  'y': 340
  wires: []
- id: 2b444ab.4ee2eb6
  type: debug
  z: d88a69c4.1942c8
  name: ''
  active: false
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 330
  'y': 390
  wires: []
- id: 363803a4.b81044
  type: mqtt in
  z: d88a69c4.1942c8
  name: sensors
  topic: sensors
  qos: '2'
  datatype: json
  broker: c38452a5.4f84e8
  nl: false
  rap: false
  inputs: 0
  x: 90
  'y': 340
  wires:
    - - ed8532c35449ea5d
- id: 7e3ea563.cfecfc
  type: function
  z: d88a69c4.1942c8
  name: Wrap
  func: |
    var msgres = msg.payload
    return msgres;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 330
  'y': 340
  wires:
    - - bf874566.5d9478
      - 1dcfd422.bd14fc
      - 5aec7656638b8a7b
- id: 1dcfd422.bd14fc
  type: debug
  z: d88a69c4.1942c8
  name: ''
  active: false
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 510
  'y': 380
  wires: []
- id: 5aec7656638b8a7b
  type: influxdb out
  z: d88a69c4.1942c8
  influxdb: 786c015f0b3c18d1
  name: ''
  measurement: ''
  precision: ''
  retentionPolicy: ''
  database: ''
  retentionPolicyV18Flux: ''
  org: ''
  bucket: ''
  x: 550
  'y': 300
  wires: []
- id: e72a9a6d97ae5b4a
  type: link in
  z: d88a69c4.1942c8
  name: DB-Insert
  links:
    - 78c90ae53c32e0c1
    - 217fc7c76bf682ea
    - bd608bdcef55352f
  x: 125
  'y': 390
  wires:
    - - ed8532c35449ea5d
