- id: 8627a08f.2f4c18
  type: tab
  label: Notifications
  disabled: false
  info: ''
- id: cb68db5a.bdbca8
  type: inject
  z: 8627a08f.2f4c18
  name: Initialize
  repeat: ''
  crontab: ''
  once: true
  onceDelay: '5'
  topic: ''
  payload: ''
  payloadType: date
  x: 100
  'y': 160
  wires:
    - - 436b2017.90da28
- id: 8b517c2b.d93ed8
  type: function
  z: 8627a08f.2f4c18
  name: Meteo
  func: |-
    var message = msg.payload.detail + '\n' + 
        "temp=" + msg.data.currently.temperature + "°C (" + msg.payload.mintemp + "°C to " + msg.payload.maxtemp + "°C) \n" +
        "humidity=" + (msg.payload.humidity * 100) + "%\n" +
        "pressure=" + msg.data.currently.pressure + "hPa\n" +
        "windspeed=" + msg.payload.windspeed + "km/h\n" +
        "winddirection=" + msg.payload.winddirection + "\n" + 
        "clouds=" + (msg.payload.clouds * 100) + "%";
        
    msg.payload = message
    return msg;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 740
  'y': 370
  wires:
    - - 0a19614dac750dc9
- id: 45d9a893.f40ca8
  type: darksky
  z: 8627a08f.2f4c18
  darksky: 56c5e5e6.d3610c
  name: Weather Forecast
  lon: '-4.5'
  lat: '48.5'
  date: ''
  time: ''
  mode: message
  lang: fr
  units: si
  x: 520
  'y': 370
  wires:
    - - 8b517c2b.d93ed8
- id: 436b2017.90da28
  type: function
  z: 8627a08f.2f4c18
  name: Fresh deploy
  func: |-
    msg.payload = "Fresh (re-)deploy !"
    return msg;
  outputs: 1
  noerr: 0
  x: 320
  'y': 160
  wires:
    - - 0a19614dac750dc9
- id: 4881ab4d.cbd20c
  type: simpletime
  z: 8627a08f.2f4c18
  name: now
  x: 610
  'y': 290
  wires:
    - - 57125e6f.c04dd
- id: f9f7f04d.3b6e58
  type: csv
  z: 8627a08f.2f4c18
  name: ''
  sep: ','
  hdrin: true
  hdrout: ''
  multi: one
  ret: \n
  temp: ''
  skip: '0'
  strings: true
  x: 490
  'y': 290
  wires:
    - - 4881ab4d.cbd20c
- id: 57125e6f.c04dd
  type: function
  z: 8627a08f.2f4c18
  name: Render day events
  func: |-
    if (msg.payload.date !== undefined) {
        
        var message, bdom, bmonth, byear;
        bparsed = msg.payload.date.split('/');
        
        if(bparsed.length == 3) {
            // year/month/day
            bdom = parseInt(bparsed[2])
            bmonth = parseInt(bparsed[1])
            byear = parseInt(bparsed[0])
            
        } else {
            // month/day
            bdom = parseInt(bparsed[1])
            bmonth = parseInt(bparsed[0])
            
        }
        
        if((bdom == msg.mydom) && (bmonth == msg.mymonthn)) {
            // date matches today
            
            if(msg.filename.indexOf('saints') !== -1) {
                message = "Saints " + msg.payload.value
                
            } else if(msg.filename.indexOf('birthday') !== -1) { 
                if(byear !== undefined) {
                    message = "Happy " + (msg.myyear - byear) + "th Birthday to " + msg.payload.value + " (" + bdom + "/" + bmonth + ")"
                } else {
                    message = "Happy Birthday to " + msg.payload.value + " (" + bdom + "/" + bmonth + ")"
                }
                
            } else {
                message = msg.payload.value
            }
            
            msg.payload = message
            return msg;
        }
    }

    // Default nothing
    return null;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 770
  'y': 290
  wires:
    - - 0a19614dac750dc9
- id: f6373746.83f598
  type: readdir
  z: 8627a08f.2f4c18
  name: Daily CSVs
  dir: /etc/tidhome/daily-events
  as: multi
  recursive: false
  outproperty: filename
  x: 320
  'y': 270
  wires:
    - - 8e4b9462.126df
- id: 8e4b9462.126df
  type: file in
  z: 8627a08f.2f4c18
  name: CSV file
  filename: ''
  format: utf8
  chunk: false
  sendError: false
  x: 360
  'y': 310
  wires:
    - - f9f7f04d.3b6e58
- id: f5632272.86a6b8
  type: inject
  z: 8627a08f.2f4c18
  name: Morning
  props: []
  repeat: ''
  crontab: 00 09 * * *
  once: false
  onceDelay: '5'
  topic: ''
  payloadType: str
  x: 100
  'y': 240
  wires:
    - - f6373746.83f598
      - e7e9239c.0be1c
      - 09304e7665f8b8b8
- id: fd76b359.51ec38
  type: inject
  z: 8627a08f.2f4c18
  name: Night
  props:
    - p: payload
    - p: topic
      vt: str
  repeat: ''
  crontab: 00 22 * * *
  once: false
  onceDelay: '5'
  topic: ''
  payload: Good night!
  payloadType: str
  x: 110
  'y': 200
  wires:
    - []
- id: 4271c741.d9a258
  type: comment
  z: 8627a08f.2f4c18
  name: Daily News
  info: ''
  x: 100
  'y': 120
  wires: []
- id: e7e9239c.0be1c
  type: function
  z: 8627a08f.2f4c18
  name: time.now()
  func: |-
    msg.time = new Date().getTime()
    return msg;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  x: 320
  'y': 370
  wires:
    - - 45d9a893.f40ca8
- id: b24260ef.c5b1e8
  type: catch
  z: 8627a08f.2f4c18
  name: ''
  scope: null
  uncaught: false
  x: 100
  'y': 80
  wires:
    - - 7ddfd97.7160228
- id: 7ddfd97.7160228
  type: link out
  z: 8627a08f.2f4c18
  name: General CatchAll
  links:
    - 1bf42829.b3e0b8
  x: 255
  'y': 80
  wires: []
- id: f55edfdb.784b5
  type: feedparse
  z: 8627a08f.2f4c18
  name: Dealabs
  url: 'https://www.dealabs.com/rss/hot'
  interval: 15
  x: 110
  'y': 520
  wires:
    - - b0f7a636.7693f
- id: fdfde972.bdcf78
  type: debug
  z: 8627a08f.2f4c18
  name: Deals
  active: false
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 890
  'y': 540
  wires: []
- id: b0f7a636.7693f
  type: json
  z: 8627a08f.2f4c18
  name: ''
  property: article
  action: ''
  pretty: false
  x: 260
  'y': 520
  wires:
    - - c92f4659.822398
- id: 683d83e8.058ebc
  type: change
  z: 8627a08f.2f4c18
  name: ''
  rules:
    - t: set
      p: payload
      pt: msg
      to: topic
      tot: msg
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 730
  'y': 580
  wires:
    - - fdfde972.bdcf78
      - e7a7cb7a8df21f27
- id: c92f4659.822398
  type: change
  z: 8627a08f.2f4c18
  name: lowercase
  rules:
    - t: set
      p: article
      pt: msg
      to: "$lowercase(article)\t"
      tot: jsonata
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 400
  'y': 520
  wires:
    - - 281623751d7a9995
- id: ff64d0d5.cdd1b
  type: trigger
  z: 8627a08f.2f4c18
  name: Watchdog
  op1: ''
  op2: ''
  op1type: nul
  op2type: pay
  duration: '1'
  extend: true
  overrideDelay: false
  units: s
  reset: ''
  bytopic: topic
  topic: topic
  outputs: 1
  x: 560
  'y': 580
  wires:
    - - 683d83e8.058ebc
- id: c86e3fdb.b856e8
  type: comment
  z: 8627a08f.2f4c18
  name: Dealabs
  info: |-
    Listen to Dealabs HotDeals
    Search keywords
    Sort topics
    Send Telegram notification
  x: 110
  'y': 480
  wires: []
- id: 09304e7665f8b8b8
  type: change
  z: 8627a08f.2f4c18
  name: Morning
  rules:
    - t: set
      p: payload
      pt: msg
      to: Good morning!
      tot: str
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 310
  'y': 230
  wires:
    - - 0a19614dac750dc9
- id: 281623751d7a9995
  type: change
  z: 8627a08f.2f4c18
  name: Includes / Excludes
  rules:
    - t: set
      p: excludes
      pt: msg
      to: tidhome.groups.groupE
      tot: global
      dc: true
    - t: set
      p: includes
      pt: msg
      to: tidhome.groups.groupD
      tot: global
      dc: true
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 200
  'y': 580
  wires:
    - - d3071673871eba6a
- id: d3071673871eba6a
  type: function
  z: 8627a08f.2f4c18
  name: Filtering
  func: |-
    pass=false

    // Includes
    for(var includeIdx in msg.includes) {
        var include = msg.includes[includeIdx]
        
        if(msg.article.indexOf(include) !== -1 ) {
            pass = true
            msg.include = include
        }
    }

    // Excludes
    if(pass == true) {
        for(var excludeIdx in msg.excludes) {
            var exclude = msg.excludes[excludeIdx]
            
            if(msg.article.indexOf(exclude) !== -1 ) {
                pass = false
                msg.exclude = exclude
            }
        }
    }

    if(pass == true)
        return msg
        
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 400
  'y': 580
  wires:
    - - 43e6adab33a9f460
- id: e7a7cb7a8df21f27
  type: link out
  z: 8627a08f.2f4c18
  name: ''
  mode: link
  links:
    - 2f30621f40aa8285
    - 69a45c84848a65e9
  x: 855
  'y': 580
  wires: []
- id: 0a19614dac750dc9
  type: link out
  z: 8627a08f.2f4c18
  name: ''
  mode: link
  links:
    - 2f30621f40aa8285
    - 69a45c84848a65e9
  x: 1015
  'y': 240
  wires: []
- id: cfeca9401ab2c043
  type: inject
  z: 8627a08f.2f4c18
  name: Special
  props:
    - p: payload
    - p: topic
      vt: str
  repeat: ''
  crontab: 00 17 * * 2
  once: false
  onceDelay: '5'
  topic: ''
  payload: ''
  payloadType: date
  x: 100
  'y': 420
  wires:
    - - 56e78fae0d72374d
- id: 56e78fae0d72374d
  type: function
  z: 8627a08f.2f4c18
  name: Week Color
  func: >-
    currentdate = new Date();

    var oneJan = new Date(currentdate.getFullYear(),0,1);

    var numberOfDays = Math.floor((currentdate - oneJan) / (24 * 60 * 60 *
    1000));

    var weekNb = Math.ceil(( currentdate.getDay() + 1 + numberOfDays) / 7);




    msg.payload = "Sortir la poubelle " + (((weekNb-1) % 2 == 0) ? "Jaune" :
    "Verte") + " :-D"

    return msg;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 760
  'y': 420
  wires:
    - - 1ba3302a5169676e
- id: 1ba3302a5169676e
  type: link out
  z: 8627a08f.2f4c18
  name: ''
  mode: link
  links:
    - c80c722c5806b680
  x: 1015
  'y': 420
  wires: []
