- id: 8627a08f.2f4c18
  type: tab
  label: Notifications
  disabled: false
  info: ''
- id: 14836b671335a268
  type: junction
  z: 8627a08f.2f4c18
  x: 980
  'y': 270
  wires:
    - - 1ba3302a5169676e
- id: 6c21ca7aee31ecb2
  type: junction
  z: 8627a08f.2f4c18
  x: 920
  'y': 210
  wires:
    - - 14836b671335a268
- id: b40f58e74745484e
  type: junction
  z: 8627a08f.2f4c18
  x: 290
  'y': 680
  wires:
    - - 31351825673be596
- id: cb68db5a.bdbca8
  type: inject
  z: 8627a08f.2f4c18
  name: Initialize
  repeat: ''
  crontab: ''
  once: true
  onceDelay: '5'
  topic: ''
  payload: ''
  payloadType: date
  x: 100
  'y': 370
  wires:
    - - 436b2017.90da28
- id: 8b517c2b.d93ed8
  type: function
  z: 8627a08f.2f4c18
  name: Render Meteo
  func: |-
    var message = msg.payload.detail + '\n' + 
        "temp=" + msg.payload.tempc + "°C\n" +
        "humidity=" + msg.payload.humidity + "%\n" +
        "pressure=" + msg.payload.pressure + "hPa\n" +
        "windspeed=" + msg.payload.windspeed + "km/h\n" +
        "winddirection=" + msg.payload.winddirection + "\n" + 
        "clouds=" + msg.payload.clouds + "%";
        
    msg.payload = message
    return msg;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 780
  'y': 280
  wires:
    - - 14836b671335a268
- id: 436b2017.90da28
  type: function
  z: 8627a08f.2f4c18
  name: Fresh deploy
  func: |-
    msg.payload = "Fresh (re-)deploy !"
    return msg;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 290
  'y': 370
  wires:
    - - 8fbe8d922b5f1997
- id: 4881ab4d.cbd20c
  type: simpletime
  z: 8627a08f.2f4c18
  name: now
  x: 610
  'y': 240
  wires:
    - - 57125e6f.c04dd
- id: f9f7f04d.3b6e58
  type: csv
  z: 8627a08f.2f4c18
  name: ''
  sep: ','
  hdrin: true
  hdrout: ''
  multi: one
  ret: \n
  temp: ''
  skip: '0'
  strings: true
  x: 470
  'y': 240
  wires:
    - - 4881ab4d.cbd20c
- id: 57125e6f.c04dd
  type: function
  z: 8627a08f.2f4c18
  name: Render day events
  func: |-
    if (msg.payload.date !== undefined) {
        
        var message, bdom, bmonth, byear;
        let bparsed = msg.payload.date.split('/');
        
        if(bparsed.length == 3) {
            // year/month/day
            bdom = parseInt(bparsed[2])
            bmonth = parseInt(bparsed[1])
            byear = parseInt(bparsed[0])
            
        } else {
            // month/day
            bdom = parseInt(bparsed[1])
            bmonth = parseInt(bparsed[0])
            
        }
        
        if((bdom == msg.mydom) && (bmonth == msg.mymonthn)) {
            // date matches today
            
            if(msg.filename.indexOf('saints') !== -1) {
                message = "Saints " + msg.payload.value
                
            } else if(msg.filename.indexOf('birthday') !== -1) { 
                if(byear !== undefined) {
                    message = "Happy " + (msg.myyear - byear) + "th Birthday to " + msg.payload.value + " (" + bdom + "/" + bmonth + ")"
                } else {
                    message = "Happy Birthday to " + msg.payload.value + " (" + bdom + "/" + bmonth + ")"
                }
                
            } else {
                message = msg.payload.value
            }
            
            msg.payload = message
            return msg;
        }
    }

    // Default nothing
    return null;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 790
  'y': 240
  wires:
    - - 14836b671335a268
- id: f6373746.83f598
  type: readdir
  z: 8627a08f.2f4c18
  name: Saints and World Days
  dir: /etc/tidhome/daily-events
  as: multi
  recursive: false
  outproperty: filename
  x: 320
  'y': 200
  wires:
    - - 8e4b9462.126df
- id: 8e4b9462.126df
  type: file in
  z: 8627a08f.2f4c18
  name: CSV file
  filename: ''
  format: utf8
  chunk: false
  sendError: false
  x: 320
  'y': 240
  wires:
    - - f9f7f04d.3b6e58
- id: f5632272.86a6b8
  type: inject
  z: 8627a08f.2f4c18
  name: Morning
  props: []
  repeat: ''
  crontab: 00 09 * * *
  once: false
  onceDelay: '5'
  topic: ''
  payloadType: str
  x: 100
  'y': 160
  wires:
    - - f6373746.83f598
      - 09304e7665f8b8b8
      - e7e9239c.0be1c
- id: 4271c741.d9a258
  type: comment
  z: 8627a08f.2f4c18
  name: Daily News
  info: ''
  x: 100
  'y': 120
  wires: []
- id: e7e9239c.0be1c
  type: function
  z: 8627a08f.2f4c18
  name: time.now()
  func: |-
    msg.time = new Date().getTime()
    return msg;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 290
  'y': 280
  wires:
    - - bfc03cc380492275
- id: b24260ef.c5b1e8
  type: catch
  z: 8627a08f.2f4c18
  name: ''
  scope: null
  uncaught: false
  x: 100
  'y': 80
  wires:
    - - 7ddfd97.7160228
- id: 7ddfd97.7160228
  type: link out
  z: 8627a08f.2f4c18
  name: General CatchAll
  links:
    - 1bf42829.b3e0b8
  x: 255
  'y': 80
  wires: []
- id: f55edfdb.784b5
  type: feedparse
  z: 8627a08f.2f4c18
  name: Dealabs
  url: 'https://www.dealabs.com/rss/hot'
  interval: 15
  x: 100
  'y': 490
  wires:
    - - 281623751d7a9995
- id: b0f7a636.7693f
  type: json
  z: 8627a08f.2f4c18
  name: ''
  property: articleCopy
  action: ''
  pretty: false
  x: 530
  'y': 490
  wires:
    - - e1f67923cf085d92
- id: c86e3fdb.b856e8
  type: comment
  z: 8627a08f.2f4c18
  name: RSS Feeds
  info: |-
    Listen to Dealabs HotDeals
    Search keywords
    Sort topics
    Send Telegram notification
  x: 110
  'y': 450
  wires: []
- id: 09304e7665f8b8b8
  type: change
  z: 8627a08f.2f4c18
  name: Morning
  rules:
    - t: set
      p: payload
      pt: msg
      to: Good morning!
      tot: str
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 280
  'y': 160
  wires:
    - - 6c21ca7aee31ecb2
- id: 281623751d7a9995
  type: change
  z: 8627a08f.2f4c18
  name: Inc / Ex
  rules:
    - t: set
      p: excludes
      pt: msg
      to: tidhome.groups.groupE
      tot: global
      dc: true
    - t: set
      p: includes
      pt: msg
      to: tidhome.groups.groupD
      tot: global
      dc: true
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 240
  'y': 490
  wires:
    - - c5569efa7d734875
- id: d3071673871eba6a
  type: function
  z: 8627a08f.2f4c18
  name: Filtering
  func: |-
    let pass=false

    // Includes
    for(var includeIdx in msg.includes) {
        var include = msg.includes[includeIdx]
        
        if (msg.articleCopy.indexOf(include) !== -1 ) {
            pass = true
            msg.include = include
        }
    }

    // Excludes
    if(pass == true) {
        for(var excludeIdx in msg.excludes) {
            var exclude = msg.excludes[excludeIdx]
            
            if (msg.articleCopy.indexOf(exclude) !== -1 ) {
                pass = false
                msg.exclude = exclude
            }
        }
    }

    if(pass == true)
        return msg
        
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 1010
  'y': 490
  wires:
    - - 8a909bab8256258f
- id: cfeca9401ab2c043
  type: inject
  z: 8627a08f.2f4c18
  name: Sortir la poubelle ...
  props:
    - p: payload
    - p: topic
      vt: str
  repeat: ''
  crontab: 00 17 * * 2
  once: false
  onceDelay: '5'
  topic: ''
  payload: ''
  payloadType: date
  x: 140
  'y': 320
  wires:
    - - 56e78fae0d72374d
- id: 56e78fae0d72374d
  type: function
  z: 8627a08f.2f4c18
  name: Verte ou Jaune ?
  func: >-
    let currentdate = new Date();

    var oneJan = new Date(currentdate.getFullYear(),0,1);

    var numberOfDays = Math.floor((currentdate.getSeconds() -
    oneJan.getSeconds()) / (24 * 60 * 60));

    var weekNb = Math.ceil(( currentdate.getDay() + 1 + numberOfDays) / 7);


    msg.payload = "Sortir la poubelle " + (((weekNb-1) % 2 == 0) ? "Jaune" :
    "Verte") + " :-D"

    return msg;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 790
  'y': 320
  wires:
    - - 14836b671335a268
- id: 1ba3302a5169676e
  type: link out
  z: 8627a08f.2f4c18
  name: Telegram CM
  mode: link
  links:
    - c80c722c5806b680
  x: 1035
  'y': 270
  wires: []
- id: d62a5899f21cd167
  type: feedparse
  z: 8627a08f.2f4c18
  name: LeMondeInformatique
  url: >-
    https://www.lemondeinformatique.fr/flux-rss/thematique/toutes-les-actualites/rss.xml
  interval: 15
  x: 140
  'y': 600
  wires:
    - - b40f58e74745484e
- id: 8a909bab8256258f
  type: function
  z: 8627a08f.2f4c18
  name: '> 6h & Render'
  func: |
    msg.dateStr = msg.article.date
    msg.date = new Date(msg.dateStr)
    msg.dateNow = new Date()
    msg.render = "[" + msg.article.title + "](" + msg.article.link + ")" 

    if(msg.date.getTime() > (msg.dateNow.getTime() - 1000 * 3600 * 6)) {
        return msg
    }
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 450
  'y': 600
  wires:
    - - 43e6adab33a9f460
- id: a45b26df013cae0c
  type: feedparse
  z: 8627a08f.2f4c18
  name: FranceTVInfo-Sciences
  url: 'https://www.francetvinfo.fr/sciences.rss'
  interval: 15
  x: 140
  'y': 640
  wires:
    - - b40f58e74745484e
- id: fce9560bc4c3314b
  type: debug
  z: 8627a08f.2f4c18
  name: News
  active: false
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 990
  'y': 560
  wires: []
- id: 080dbe7f6708bea1
  type: change
  z: 8627a08f.2f4c18
  name: Assign news
  rules:
    - t: set
      p: payload
      pt: msg
      to: render
      tot: msg
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 800
  'y': 600
  wires:
    - - fce9560bc4c3314b
      - 4da44a73cf53899e
- id: 43e6adab33a9f460
  type: trigger
  z: 8627a08f.2f4c18
  name: Rate Limit
  op1: ''
  op2: ''
  op1type: nul
  op2type: pay
  duration: '5'
  extend: true
  overrideDelay: false
  units: min
  reset: ''
  bytopic: topic
  topic: topic
  outputs: 1
  x: 630
  'y': 600
  wires:
    - - 080dbe7f6708bea1
- id: e1f67923cf085d92
  type: change
  z: 8627a08f.2f4c18
  name: LowerCase
  rules:
    - t: set
      p: articleCopy
      pt: msg
      to: $lowercase(articleCopy)
      tot: jsonata
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 670
  'y': 490
  wires:
    - - d3071673871eba6a
- id: 8011356333a316f0
  type: comment
  z: 8627a08f.2f4c18
  name: Schedulers
  info: ''
  x: 100
  'y': 790
  wires: []
- id: f2f40dc3da630cc9
  type: sunrise
  z: 8627a08f.2f4c18
  name: ''
  lat: '48.5'
  lon: '-4.5'
  start: sunrise
  end: sunset
  soff: '0'
  eoff: '15'
  x: 110
  'y': 840
  wires:
    - []
    - - 5f629250b70e5979
- id: 5f629250b70e5979
  type: switch
  z: 8627a08f.2f4c18
  name: Day or Night ?
  property: payload
  propertyType: msg
  rules:
    - t: eq
      v: '1'
      vt: num
    - t: eq
      v: '0'
      vt: num
  checkall: 'true'
  repair: false
  outputs: 2
  x: 300
  'y': 840
  wires:
    - []
    - - 7735f46c01861b34
- id: 7735f46c01861b34
  type: function
  z: 8627a08f.2f4c18
  name: Shutters down !
  func: |-
    return [
        {
            payload: "This is night !"
        },
        {
            action: "CLOSE"
        }
    ]
  outputs: 2
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 500
  'y': 880
  wires:
    - - 4d87ac10f93853bc
    - - fecb20f01567e4a8
- id: fecb20f01567e4a8
  type: link out
  z: 8627a08f.2f4c18
  name: Config-Schedulers-Out
  mode: link
  links:
    - f576c3026a84db30
  x: 695
  'y': 890
  wires: []
- id: 920a6d44fc9d1a0a
  type: link out
  z: 8627a08f.2f4c18
  name: Telegram C
  mode: link
  links:
    - 2f30621f40aa8285
  x: 715
  'y': 370
  wires: []
- id: 20def1f1498e3e18
  type: comment
  z: 8627a08f.2f4c18
  name: To Telegram C
  info: ''
  x: 820
  'y': 370
  wires: []
- id: 040cebcfbd0283a1
  type: comment
  z: 8627a08f.2f4c18
  name: To Telegram CM
  info: ''
  x: 1100
  'y': 230
  wires: []
- id: e9131fd2804af10b
  type: feedparse
  z: 8627a08f.2f4c18
  name: TechRadar-Computing
  url: 'https://www.techradar.com/rss/news/computing'
  interval: 15
  ignorefirst: false
  x: 140
  'y': 680
  wires:
    - - b40f58e74745484e
- id: a212439a732896f1
  type: feedparse
  z: 8627a08f.2f4c18
  name: TechRadar-Tech
  url: 'https://www.techradar.com/rss/news/world-of-tech'
  interval: 15
  ignorefirst: false
  x: 120
  'y': 720
  wires:
    - - b40f58e74745484e
- id: 8fbe8d922b5f1997
  type: trigger
  z: 8627a08f.2f4c18
  name: Rate Limit
  op1: ''
  op2: ''
  op1type: nul
  op2type: pay
  duration: '5'
  extend: true
  overrideDelay: false
  units: min
  reset: ''
  bytopic: topic
  topic: topic
  outputs: 1
  x: 530
  'y': 370
  wires:
    - - 920a6d44fc9d1a0a
- id: bfc03cc380492275
  type: openweathermap
  z: 8627a08f.2f4c18
  name: Brest/France
  wtype: current
  lon: ''
  lat: ''
  city: Brest
  country: FR
  language: en
  x: 490
  'y': 280
  wires:
    - - 8b517c2b.d93ed8
- id: 4d87ac10f93853bc
  type: link out
  z: 8627a08f.2f4c18
  name: Telegram C
  mode: link
  links:
    - 2f30621f40aa8285
  x: 695
  'y': 850
  wires: []
- id: 4da44a73cf53899e
  type: link out
  z: 8627a08f.2f4c18
  name: Telegram C
  mode: link
  links:
    - 2f30621f40aa8285
  x: 955
  'y': 600
  wires: []
- id: 286cf49303ab5ee9
  type: comment
  z: 8627a08f.2f4c18
  name: To Telegram C
  info: ''
  x: 1060
  'y': 600
  wires: []
- id: 40bb6b4fc46482fe
  type: comment
  z: 8627a08f.2f4c18
  name: To Telegram C
  info: ''
  x: 800
  'y': 850
  wires: []
- id: 475ad60d47ef850f
  type: json
  z: 8627a08f.2f4c18
  name: ''
  property: articleCopy
  action: ''
  pretty: false
  x: 520
  'y': 680
  wires:
    - - 1f277bad7ccd171b
- id: 31351825673be596
  type: change
  z: 8627a08f.2f4c18
  name: articleCopy
  rules:
    - t: set
      p: articleCopy
      pt: msg
      to: article
      tot: msg
      dc: true
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 380
  'y': 680
  wires:
    - - 475ad60d47ef850f
- id: 1f277bad7ccd171b
  type: change
  z: 8627a08f.2f4c18
  name: assign
  rules:
    - t: set
      p: input
      pt: msg
      to: article
      tot: msg
      dc: true
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 640
  'y': 680
  wires:
    - - 1cbd88762507b2d8
- id: 1cbd88762507b2d8
  type: GoRules
  z: 8627a08f.2f4c18
  name: RSS Rules
  ruleFile: /etc/tidhome/rules/RSS-rules.json
  x: 780
  'y': 680
  wires:
    - - ed8bdee63a5d4662
- id: ed8bdee63a5d4662
  type: switch
  z: 8627a08f.2f4c18
  name: Filter?
  property: output.filter
  propertyType: msg
  rules:
    - t: eq
      v: 'yes'
      vt: str
  checkall: 'true'
  repair: false
  outputs: 1
  x: 920
  'y': 680
  wires:
    - - 8a909bab8256258f
- id: c5569efa7d734875
  type: change
  z: 8627a08f.2f4c18
  name: Copy article
  rules:
    - t: set
      p: articleCopy
      pt: msg
      to: article
      tot: msg
      dc: true
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 390
  'y': 490
  wires:
    - - b0f7a636.7693f
