- id: b1782abc.430f38
  type: tab
  label: Sensors-WebRelay
  disabled: false
  info: ''
- id: add1e3abafaf542e
  type: junction
  z: b1782abc.430f38
  x: 1120
  'y': 530
  wires:
    - - 5b354d74db3c3466
      - 217fc7c76bf682ea
- id: 0edaade20969311b
  type: junction
  z: b1782abc.430f38
  x: 1380
  'y': 710
  wires:
    - - 3e4d792744058a92
      - 217fc7c76bf682ea
- id: ce07888f46a79c45
  type: junction
  z: b1782abc.430f38
  x: 890
  'y': 760
  wires:
    - - 937e6892618fdb6b
      - 8108d50cd2c5b67c
- id: a5756da99a56965e
  type: junction
  z: b1782abc.430f38
  x: 1060
  'y': 870
  wires:
    - - 7e1ec77294b7e482
      - 74c89456e710ef6d
- id: e2c89ae6.57aa1
  type: http request
  z: b1782abc.430f38
  name: Web Relays
  method: GET
  ret: obj
  paytoqs: ignore
  url: 'http://ioteleinfo.local/status'
  tls: ''
  persist: true
  proxy: ''
  insecureHTTPParser: false
  authType: ''
  senderr: false
  headers: []
  x: 360
  'y': 90
  wires:
    - - 7c54b8f2.2432a
      - 7e2f7c263a132298
- id: 1757f9f9.180a86
  type: inject
  z: b1782abc.430f38
  name: Poll Web Relays (60s)
  repeat: '60'
  crontab: ''
  once: false
  onceDelay: ''
  topic: ''
  payload: ''
  payloadType: str
  x: 150
  'y': 90
  wires:
    - - e2c89ae6.57aa1
- id: bf66c587.e16b18
  type: mqtt out
  z: b1782abc.430f38
  name: sensors/xxx/nodes/...
  topic: ''
  qos: ''
  retain: ''
  broker: c38452a5.4f84e8
  x: 790
  'y': 80
  wires: []
- id: 220263b.bb9aa1c
  type: catch
  z: b1782abc.430f38
  name: ''
  scope: null
  uncaught: false
  x: 100
  'y': 30
  wires:
    - - 5d10dd0b.1db574
- id: 5d10dd0b.1db574
  type: link out
  z: b1782abc.430f38
  name: General CatchAll
  links:
    - 1bf42829.b3e0b8
  x: 255
  'y': 30
  wires: []
- id: 7c54b8f2.2432a
  type: debug
  z: b1782abc.430f38
  name: WR-Debug-Poll
  active: false
  tosidebar: true
  console: false
  tostatus: false
  complete: payload
  targetType: msg
  statusVal: ''
  statusType: auto
  x: 550
  'y': 140
  wires: []
- id: e2d7dc14.f1a8a8
  type: comment
  z: b1782abc.430f38
  name: Actors - MQTT push
  info: ''
  x: 130
  'y': 170
  wires: []
- id: dda2b638.2a5f7
  type: mqtt in
  z: b1782abc.430f38
  name: actors/iotheaters/switch
  topic: actors/iotheaters/switch
  qos: '2'
  datatype: json
  broker: c38452a5.4f84e8
  inputs: 0
  x: 140
  'y': 210
  wires:
    - - f8329ea7.84c6d8
- id: f8329ea7.84c6d8
  type: http request
  z: b1782abc.430f38
  name: Switch Web Relays
  method: GET
  ret: txt
  paytoqs: ignore
  url: 'http://ioteleinfo.local/relays/set?id={{{payload.id}}}&value=-1'
  tls: ''
  persist: false
  proxy: ''
  insecureHTTPParser: false
  authType: ''
  senderr: false
  headers: []
  x: 570
  'y': 210
  wires:
    - - eeed3c1e.9602e8
- id: eeed3c1e.9602e8
  type: debug
  z: b1782abc.430f38
  name: ''
  active: false
  console: 'false'
  complete: 'true'
  x: 800
  'y': 210
  wires: []
- id: a9a5a446.2c7cb
  type: websocket in
  z: b1782abc.430f38
  name: WebRelay
  server: ''
  client: '26438802.204788'
  x: 100
  'y': 380
  wires:
    - - 2812070e.894da8
      - ac2d43ea.e2eaf
      - 67d26f68.ac9028
      - c97606c5.d54558
- id: 6efd389b.03b1
  type: switch
  z: b1782abc.430f38
  name: sensors value
  property: sensors
  propertyType: msg
  rules:
    - t: hask
      v: temperature
      vt: str
    - t: hask
      v: humidity
      vt: str
    - t: else
  checkall: 'true'
  repair: false
  outputs: 3
  x: 670
  'y': 510
  wires:
    - - b629ec5a.2b4f78
    - - 16258a34.5ce016
    - []
- id: b629ec5a.2b4f78
  type: function
  z: b1782abc.430f38
  name: Sensors-Temperature
  func: |-
    var msgres =  {
        payload: {
            topic: "teleinfo-temperature-wr-Garage",
            payload: [
                { "value": Number(msg.sensors.temperature) },
                { "type": "temperature", "location": "wr-Garage" }
            ],
            measurement: "sensors"
        }
    }

    return msgres;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 950
  'y': 510
  wires:
    - - add1e3abafaf542e
- id: 16258a34.5ce016
  type: function
  z: b1782abc.430f38
  name: Sensors-Humidity
  func: |-
    var msgres =  {
        payload: {
            topic: "teleinfo-humidity-wr-Garage",
            payload: [
                { "value": Number(msg.sensors.humidity) },
                { "type": "humidity", "location": "wr-Garage" }
            ],
            measurement: "sensors"
        }
    }

    return msgres;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 940
  'y': 550
  wires:
    - - add1e3abafaf542e
- id: 2812070e.894da8
  type: debug
  z: b1782abc.430f38
  name: WR Debug
  active: false
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 280
  'y': 340
  wires: []
- id: f080b42a.8ae208
  type: debug
  z: b1782abc.430f38
  name: WR-SensorsDebug
  active: false
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 680
  'y': 560
  wires: []
- id: ac2d43ea.e2eaf
  type: switch
  z: b1782abc.430f38
  name: relays
  property: relays
  propertyType: msg
  rules:
    - t: nnull
  checkall: 'true'
  repair: false
  outputs: 1
  x: 260
  'y': 380
  wires:
    - - a5380107f47958f6
- id: d66f7b10.e7534
  type: function
  z: b1782abc.430f38
  name: Relays-OnOff
  func: |-
    var msgres =  {
        payload: {
            payload: [
                { "value": Number(msg.payload.value) },
                { "type": "plug-onoff", "location": "wr-Garage-" + msg.payload.id }
            ],
            measurement: "sensors"
        }
    }

    return msgres;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 990
  'y': 380
  wires:
    - - 217fc7c76bf682ea
- id: 7755fd51.b4d8f4
  type: debug
  z: b1782abc.430f38
  name: WR-RelaysDebug
  active: false
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 680
  'y': 420
  wires: []
- id: 67d26f68.ac9028
  type: switch
  z: b1782abc.430f38
  name: sensors
  property: sensors
  propertyType: msg
  rules:
    - t: nnull
  checkall: 'true'
  repair: false
  outputs: 1
  x: 270
  'y': 420
  wires:
    - - 454b51ddb4afb37d
- id: c97606c5.d54558
  type: switch
  z: b1782abc.430f38
  name: teleinfo
  property: teleinfo
  propertyType: msg
  rules:
    - t: nnull
  checkall: 'true'
  repair: false
  outputs: 1
  x: 270
  'y': 460
  wires:
    - - 1f15f03f0befad41
- id: 10349fb3.8e444
  type: split
  z: b1782abc.430f38
  name: ''
  splt: \n
  spltType: str
  arraySplt: 1
  arraySpltType: len
  stream: false
  addname: ''
  x: 830
  'y': 380
  wires:
    - - d66f7b10.e7534
- id: b7f3c41.7550bb8
  type: change
  z: b1782abc.430f38
  name: keys
  rules:
    - t: set
      p: payload
      pt: msg
      to: relays
      tot: msg
      dc: true
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 640
  'y': 380
  wires:
    - - 10349fb3.8e444
- id: 4041416e2b11e83f
  type: debug
  z: b1782abc.430f38
  name: WR-TeleinfoDebug
  active: false
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 680
  'y': 710
  wires: []
- id: 3e4d792744058a92
  type: debug
  z: b1782abc.430f38
  name: StorageDebug
  active: false
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 1500
  'y': 700
  wires: []
- id: 8175abc180c732e4
  type: mqtt in
  z: b1782abc.430f38
  name: actors/iotheaters/set
  topic: actors/iotheaters/set
  qos: '2'
  datatype: json
  broker: c38452a5.4f84e8
  nl: false
  rap: false
  inputs: 0
  x: 130
  'y': 260
  wires:
    - - 6b78b06d6d132a3b
- id: bf76f115523ab776
  type: debug
  z: b1782abc.430f38
  name: ''
  active: false
  console: 'false'
  complete: 'true'
  x: 800
  'y': 260
  wires: []
- id: 046ac47846e9e56f
  type: http request
  z: b1782abc.430f38
  name: Set Web Relays
  method: GET
  ret: txt
  paytoqs: ignore
  url: >-
    http://ioteleinfo.local/relays/set?id={{{payload.id}}}&state={{{payload.value}}}
  tls: ''
  persist: false
  proxy: ''
  insecureHTTPParser: false
  authType: ''
  senderr: false
  headers: []
  x: 560
  'y': 260
  wires:
    - - bf76f115523ab776
- id: 6b78b06d6d132a3b
  type: delay
  z: b1782abc.430f38
  name: ''
  pauseType: rate
  timeout: '500'
  timeoutUnits: milliseconds
  rate: '1'
  nbRateUnits: '0.1'
  rateUnits: second
  randomFirst: '1'
  randomLast: '5'
  randomUnits: seconds
  drop: false
  allowrate: false
  outputs: 1
  x: 350
  'y': 260
  wires:
    - - 046ac47846e9e56f
- id: 7e2f7c263a132298
  type: function
  z: b1782abc.430f38
  name: Parse WebRelays
  func: |-
    // name: Parse web relays
    // outputs: 1
    var outputMsgs = []
    var displayMsg = ""
    var timestampH = new Date().toISOString()
    var timestamp = new Date().getTime()

    for (var i in msg.payload.relays) {
        
        let relayId = msg.payload.relays[i].id
        let relayDesc = msg.payload.relays[i].description
        let relayValue = msg.payload.relays[i].value
        let type = 'toggle'
        let entry = 0
        
        var msgS = {}
        msgS.topic = 'sensors/iotheaters/nodes/' + relayId + '/entries/' + entry + '/events/' + type;
        msgS.payload = { 
            "gateway":"iotheaters",
            "id": relayId,
            "entry": entry,
            "type": type,
            "value": relayValue,
            "timestamp": timestamp,
            "timestamp-human": timestampH
        }
        displayMsg += relayDesc + "(" + relayId + ")=" + relayValue + "; "
        outputMsgs.push(msgS);
    }

    node.status({ fill:"blue", shape:"dot", text: displayMsg });

    return [ outputMsgs ];
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 560
  'y': 80
  wires:
    - - bf66c587.e16b18
- id: 5b354d74db3c3466
  type: debug
  z: b1782abc.430f38
  name: WR W Debug
  active: false
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 1300
  'y': 530
  wires: []
- id: c65cb5485f659160
  type: split
  z: b1782abc.430f38
  name: ''
  splt: \n
  spltType: str
  arraySplt: 1
  arraySpltType: len
  stream: false
  addname: topic
  x: 770
  'y': 670
  wires:
    - - 344955f96799a3bd
      - 549ac02050217f3d
- id: bec90f8452d9f39a
  type: change
  z: b1782abc.430f38
  name: keys
  rules:
    - t: set
      p: payload
      pt: msg
      to: teleinfo
      tot: msg
      dc: true
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 640
  'y': 670
  wires:
    - - c65cb5485f659160
- id: 96a4ca6603fc71d9
  type: link in
  z: b1782abc.430f38
  name: In-WS-Teleinfo
  links:
    - 1f15f03f0befad41
  x: 545
  'y': 670
  wires:
    - - bec90f8452d9f39a
      - 4041416e2b11e83f
- id: 174f858dfae1238b
  type: comment
  z: b1782abc.430f38
  name: Teleinfo Events
  info: ''
  x: 610
  'y': 620
  wires: []
- id: 1f15f03f0befad41
  type: link out
  z: b1782abc.430f38
  name: Out-WS-Teleinfo
  mode: link
  links:
    - 96a4ca6603fc71d9
  x: 425
  'y': 460
  wires: []
- id: 9f6adedc9ca772ef
  type: switch
  z: b1782abc.430f38
  name: ''
  property: topic
  propertyType: msg
  rules:
    - t: cont
      v: BBRH
      vt: str
    - t: else
  checkall: 'false'
  repair: false
  outputs: 2
  x: 780
  'y': 770
  wires:
    - - ce07888f46a79c45
      - a5756da99a56965e
    - - a5756da99a56965e
- id: 37aa0a253b8b6972
  type: function
  z: b1782abc.430f38
  name: Insert X
  func: >-
    // sensors_value

    let fields = { "value": Number(msg.payload) }

    let tags =   { "type": "teleinfo-" + msg.topic, "location": "main" }


    var msgres1 =  {
        topic: "teleinfo-" + msg.topic,
        payload: {
            payload: [ fields, tags ],
            measurement: "sensors"
        }
    }


    // sensors_teleinfo_X

    let namedFieldName = "teleinfo_" + msg.topic

    let namedFields = { [namedFieldName]: Number(msg.payload) }

    var namedTags = { "location": "main" }


    var msgres2 = {
        topic: namedFieldName,
        payload: {
            payload: [namedFields, namedTags],
            measurement: "sensors"
        }
    }


    // live info

    node.status({ fill: "blue", shape: "dot", text: msg.topic + ": " +
    Number(msg.payload) });


    return [
        msgres1,
        msgres2
    ]
  outputs: 2
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 1290
  'y': 890
  wires:
    - - 0edaade20969311b
    - - 0edaade20969311b
- id: 7e1ec77294b7e482
  type: function
  z: b1782abc.430f38
  name: IsNumeric
  func: |
    function isNumeric(n) { 
        return !isNaN(parseFloat(n)) && isFinite(n); 
    }

    // convert to numeric if possible
    if (isNumeric(msg.payload)) {
        node.status({ fill: "blue", shape: "dot", text: msg.topic + ": " + Number(msg.payload) });
        return { topic: msg.topic, payload: Number(msg.payload) }
    }
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 1150
  'y': 890
  wires:
    - - 37aa0a253b8b6972
- id: 4d497c789965be0b
  type: comment
  z: b1782abc.430f38
  name: Sensors Events
  info: ''
  x: 610
  'y': 460
  wires: []
- id: d63aa9d36b927771
  type: link in
  z: b1782abc.430f38
  name: In-WS-Sensors
  links:
    - 454b51ddb4afb37d
  x: 545
  'y': 500
  wires:
    - - f080b42a.8ae208
      - 6efd389b.03b1
- id: 454b51ddb4afb37d
  type: link out
  z: b1782abc.430f38
  name: Out-WS-Sensors
  mode: link
  links:
    - d63aa9d36b927771
  x: 425
  'y': 420
  wires: []
- id: a5b4510db50dad64
  type: comment
  z: b1782abc.430f38
  name: Sensors Relays
  info: ''
  x: 610
  'y': 340
  wires: []
- id: 4a624afb78acff75
  type: link in
  z: b1782abc.430f38
  name: In-WS-Relays
  links:
    - a5380107f47958f6
  x: 545
  'y': 380
  wires:
    - - b7f3c41.7550bb8
      - 7755fd51.b4d8f4
- id: a5380107f47958f6
  type: link out
  z: b1782abc.430f38
  name: Out-WS-Relays
  mode: link
  links:
    - 4a624afb78acff75
  x: 425
  'y': 380
  wires: []
- id: 344955f96799a3bd
  type: function
  z: b1782abc.430f38
  name: Global
  func: |-
    function isNumeric(n) {
        return !isNaN(parseFloat(n)) && isFinite(n);
    }

    // convert to numeric if possible
    if (isNumeric(msg.payload)) {
        msg.payload = Number(msg.payload)
    }

    global.set("tidhome_teleinfo." + msg.topic, msg.payload)
    return { topic: msg.topic, payload: msg.payload }
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 900
  'y': 670
  wires:
    - - 9f6adedc9ca772ef
- id: 217fc7c76bf682ea
  type: link out
  z: b1782abc.430f38
  name: link out 2
  mode: link
  links:
    - e72a9a6d97ae5b4a
  x: 1445
  'y': 400
  wires: []
- id: 937e6892618fdb6b
  type: function
  z: b1782abc.430f38
  name: Indexes Wh
  func: |-
    var periods = [
        "BBRHPJB",
        "BBRHCJB",
        "BBRHPJW",
        "BBRHCJW",
        "BBRHPJR",
        "BBRHCJR"
    ]

    let text = ""
    let teleinfoTotal = 0
    let fields = {}

    for(var period in periods) {
        // get index from memory
        let idxPeriod = Number(global.get("tidhome_teleinfo." + periods[period]))
        
        switch (periods[period]) {
            case "BBRHPJB":
                if (idxPeriod > 0) { 
                    // set DB index for an update
                    fields["teleinfo_" + periods[period]] = idxPeriod

                    fields["teleinfo_HCHP"] = idxPeriod
                }
                break
            case "BBRHCJB":
                if (idxPeriod > 0) { 
                    // set DB index for an update
                    fields["teleinfo_" + periods[period]] = idxPeriod

                    fields["teleinfo_HCHC"] = idxPeriod
                }
                break
            default:
                // set DB index for an update
                fields["teleinfo_" + periods[period]] = idxPeriod
                break
        }

        // compute total
        teleinfoTotal += idxPeriod
        // message for debug
        text += ((text.length > 0) ? " / " : "") + periods[period].substring(3) + ': ' + idxPeriod
    }

    // Index fields
    fields["teleinfo_Wh_Total"] = Number(teleinfoTotal)    

    let tags =   { "location": "main" }

    var msg =  {
        topic: "teleinfo",
        payload: {
            payload: [ fields, tags ],
            measurement: "sensors"
        }
    }

    node.status({ fill: "blue", shape: "dot", text: text });

    return msg
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 1010
  'y': 740
  wires:
    - - 2c1277c0c3ca0af4
- id: 74c89456e710ef6d
  type: debug
  z: b1782abc.430f38
  name: WR-Teleinfo-Periods-Debug
  active: false
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 1210
  'y': 850
  wires: []
- id: 8108d50cd2c5b67c
  type: function
  z: b1782abc.430f38
  name: int(PTEC)
  func: |-
    // update period as integer (1=HPJB, 2=HCJB, 3=HPJW, ...)
    let period = -1
    let topic = 'PTEC_int'
    if(msg.topic.startsWith('BBR')) {
        switch(msg.topic) {
            case 'BBRHPJB':
                period = 1
                break
            case 'BBRHCJB':
                period = 2
                break
            case 'BBRHPJW':
                period = 3
                break
            case 'BBRHCJW':
                period = 4
                break
            case 'BBRHPJR':
                period = 5
                break
            case 'BBRHCJR':
                period = 6
                break
        }

        if(period > 0) {
            global.set("tidhome_teleinfo." + topic, Number(period))

            return {
                topic: topic,
                payload: period
            }
        }
    }
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 1000
  'y': 790
  wires:
    - - a5756da99a56965e
- id: 2c1277c0c3ca0af4
  type: delay
  z: b1782abc.430f38
  name: 1 msg/m
  pauseType: timed
  timeout: '5'
  timeoutUnits: seconds
  rate: '1'
  nbRateUnits: '1'
  rateUnits: minute
  randomFirst: '1'
  randomLast: '5'
  randomUnits: seconds
  drop: true
  allowrate: false
  outputs: 1
  x: 1230
  'y': 710
  wires:
    - - 0edaade20969311b
- id: 549ac02050217f3d
  type: debug
  z: b1782abc.430f38
  name: WR-TeleinfoDebug
  active: false
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 940
  'y': 630
  wires: []
