- id: d06e385b.de11c8
  type: tab
  label: Sensors-Jeelink
  disabled: false
  info: ''
- id: 613655ae.7a0704
  type: serial in
  z: d06e385b.de11c8
  name: Jeelink
  serial: 4c23cd92.778204
  x: 90
  'y': 120
  wires:
    - - 3d01e9886263c391
- id: f20c9be2.db11d8
  type: mqtt out
  z: d06e385b.de11c8
  name: sensors/xxx/nodes/...
  topic: ''
  qos: ''
  retain: ''
  broker: c38452a5.4f84e8
  x: 760
  'y': 120
  wires: []
- id: ec13faf7.4b286
  type: catch
  z: d06e385b.de11c8
  name: ''
  scope: null
  uncaught: false
  x: 100
  'y': 80
  wires:
    - - 64dacb8b.d2f3e4
- id: 64dacb8b.d2f3e4
  type: link out
  z: d06e385b.de11c8
  name: General CatchAll
  links:
    - 1bf42829.b3e0b8
  x: 255
  'y': 80
  wires: []
- id: b10f5d4d.ca99e8
  type: debug
  z: d06e385b.de11c8
  name: Debug
  active: false
  tosidebar: true
  console: true
  tostatus: false
  complete: 'true'
  targetType: full
  x: 920
  'y': 170
  wires: []
- id: 823b2da3.07a708
  type: function
  z: d06e385b.de11c8
  name: query insert
  func: |-
    var msgres =  {
        payload: {
            payload: [
                { "value": Number(msg.payload.value) },
                { "type": msg.payload.type, "location": msg.topic }
            ],
            measurement: "sensors"
        }
    }

    return msgres;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 930
  'y': 210
  wires:
    - - 9502284c.4f29f8
- id: 9502284c.4f29f8
  type: mqtt out
  z: d06e385b.de11c8
  name: sensors
  topic: sensors
  qos: ''
  retain: ''
  broker: c38452a5.4f84e8
  x: 1140
  'y': 210
  wires: []
- id: 9826adfd.b0d9b
  type: switch
  z: d06e385b.de11c8
  name: Sort
  property: payload.type
  propertyType: msg
  rules:
    - t: eq
      v: temperature
      vt: str
    - t: eq
      v: humidity
      vt: str
    - t: eq
      v: pressure
      vt: str
    - t: else
  checkall: 'true'
  repair: false
  outputs: 4
  x: 710
  'y': 220
  wires:
    - - 823b2da3.07a708
      - b10f5d4d.ca99e8
    - - 823b2da3.07a708
      - b10f5d4d.ca99e8
    - - 823b2da3.07a708
      - b10f5d4d.ca99e8
    - - eefff2a7.d27e98
- id: eefff2a7.d27e98
  type: debug
  z: d06e385b.de11c8
  name: Not looked
  active: false
  tosidebar: true
  console: true
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 930
  'y': 250
  wires: []
- id: 3d01e9886263c391
  type: function
  z: d06e385b.de11c8
  name: Parse JeeLink
  func: |-
    // name: Parse JeeLink
    // outputs: 1
    var outputMsgs = []
    timestampH = new Date().toISOString()
    timestamp = new Date().getTime()

    var s = msg.payload.split(' ')
    if(s[0] === 'ROOM') {
        var type = ''
        var nodeid = parseInt(s[1])
        // var nodeid5 = ("00000" + nodeid).slice (-5)
        var entry = parseInt(s[2])
        var value = s[4].replace(/(\r\n|\n|\r)/gm,"");
        if(s[3] == 0) {
          type = 'temperature';
          value = value / 10;
        } else if(s[3] == 1) {
          type = 'humidity';
          value = value / 10;
        } else if(s[3] == 2) {
          type = 'pressure';
          value = value / 10;
        } else if(s[3] == 3) {
          type = 'light';
        } else if(s[3] == 4 && value !== 0) {
          type = 'battery';
          value = value / 100;
        } else if(s[3] == 5) {
          type = 'soil';
        } else if(s[3] == 6) {
          type = 'toggle';
          value = parseInt(value);
        }
        
        if(type !== '') {
            var msgJ = {}
            msgJ.topic = 'sensors/rfm868usb/nodes/' + nodeid + '/entries/' + entry + '/events/' + type;
            msgJ.payload = { 
                "gateway":"rfm868usb",
                "id": nodeid,
                "entry": entry,
                "type": type,
                "value": value,
                "timestamp": timestamp,
                "timestamp-human": timestampH
            }
            node.status({ fill:"blue", shape:"dot", text: msg.payload });
            outputMsgs.push(msgJ);
        } else {
          node.status({ fill:"red", shape:"dot", text: msg.payload });
        }
        
        //setTimeout(function() { this.status({}); }, 500);
        //this.status({fill:"green",shape:"dot",text:"processed"});
    }

    return [ outputMsgs ];
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 320
  'y': 120
  wires:
    - - 9826adfd.b0d9b
      - f20c9be2.db11d8
      - e056629cc98f1ea1
- id: e056629cc98f1ea1
  type: trigger
  z: d06e385b.de11c8
  name: Watchdog
  op1: ''
  op2: ''
  op1type: nul
  op2type: pay
  duration: '1'
  extend: true
  overrideDelay: false
  units: hr
  reset: ''
  bytopic: topic
  topic: topic
  outputs: 1
  x: 520
  'y': 290
  wires:
    - - 98dfd3e21cde4eac
- id: 98dfd3e21cde4eac
  type: debug
  z: d06e385b.de11c8
  name: JL W Debug
  active: true
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 710
  'y': 290
  wires: []
