- id: f6aef2f1.dd52e8
  type: tab
  label: Telegram
  disabled: false
  info: ''
- id: 42b9a882.0c7548
  type: catch
  z: f6aef2f1.dd52e8
  name: ''
  scope: null
  uncaught: false
  x: 100
  'y': 80
  wires:
    - - 98c9017f.76bca
- id: 98c9017f.76bca
  type: link out
  z: f6aef2f1.dd52e8
  name: General CatchAll
  links:
    - 1bf42829.b3e0b8
  x: 255
  'y': 80
  wires: []
- id: d020562c.8333a8
  type: telegram sender
  z: f6aef2f1.dd52e8
  name: Send
  bot: 4fc69d2d.235124
  outputs: 1
  x: 870
  'y': 160
  wires:
    - - fa16035d.0f0fd8
- id: fa16035d.0f0fd8
  type: debug
  z: f6aef2f1.dd52e8
  name: Status
  active: true
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  x: 1030
  'y': 160
  wires: []
- id: 20133b84.b44ca4
  type: mqtt in
  z: f6aef2f1.dd52e8
  name: notifications/telegram
  topic: notifications/telegram
  qos: '2'
  datatype: auto
  broker: c38452a5.4f84e8
  inputs: 0
  x: 140
  'y': 160
  wires:
    - - e8dfc067.c65a1
      - efdc44ad7838b791
- id: b52ace9b.c4f7f
  type: function
  z: f6aef2f1.dd52e8
  name: Render notification event
  func: |-
    msg.payload = {
        "chatId": msg.telegramrecipients,
        "type": "message",
        "options": { "parse_mode": "Markdown" },
        "content": msg.payload
    }
    return msg;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 680
  'y': 160
  wires:
    - - d020562c.8333a8
- id: 586ca451.0700d4
  type: comment
  z: f6aef2f1.dd52e8
  name: Publish Telegram message to K
  info: ''
  x: 170
  'y': 120
  wires: []
- id: e8dfc067.c65a1
  type: credentials
  z: f6aef2f1.dd52e8
  name: K
  props:
    - value: telegramrecipients
      type: msg
  x: 320
  'y': 160
  wires:
    - - ec21e2dfc2fb77be
- id: f7290145.4541
  type: telegram command
  z: f6aef2f1.dd52e8
  name: /help
  command: /help
  bot: 4fc69d2d.235124
  strict: false
  hasresponse: false
  outputs: 2
  x: 90
  'y': 350
  wires:
    - - 2a90a04d.2f6e98
    - []
- id: 42720d76.713b3c
  type: telegram sender
  z: f6aef2f1.dd52e8
  name: Send
  bot: 4fc69d2d.235124
  outputs: 1
  x: 450
  'y': 300
  wires:
    - - 20cc8013.f8d02
- id: 2a90a04d.2f6e98
  type: function
  z: f6aef2f1.dd52e8
  name: ''
  func: >-
    var helpMessage = "/help - shows help\n";

    helpMessage += "/status - request for status\n";

    helpMessage += "/meteo - request for meteo\n";


    helpMessage += "Your chat id is " + msg.payload.chatId + "\n";

    helpMessage += "You are welcome: "+ msg.originalMessage.from.username +
    "\n";


    msg.payload.content = helpMessage;

    return msg;
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  x: 270
  'y': 300
  wires:
    - - 42720d76.713b3c
- id: 20cc8013.f8d02
  type: debug
  z: f6aef2f1.dd52e8
  name: Status
  active: false
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  x: 620
  'y': 300
  wires: []
- id: 118b2ea9.b320d1
  type: telegram command
  z: f6aef2f1.dd52e8
  name: /start
  command: /start
  bot: 4fc69d2d.235124
  strict: false
  hasresponse: false
  useregex: false
  removeregexcommand: false
  outputs: 1
  x: 90
  'y': 300
  wires:
    - - 2a90a04d.2f6e98
- id: a7974ba.f02b438
  type: comment
  z: f6aef2f1.dd52e8
  name: HELP
  info: ''
  x: 90
  'y': 260
  wires: []
- id: 37f44010.1082a
  type: telegram command
  z: f6aef2f1.dd52e8
  name: /volets
  command: /volets
  description: ''
  registercommand: false
  language: ''
  bot: 4fc69d2d.235124
  strict: false
  hasresponse: false
  useregex: false
  removeregexcommand: false
  outputs: 1
  x: 90
  'y': 510
  wires:
    - - 6e059c3f.301864
- id: 8d0d171f.e98ce
  type: comment
  z: f6aef2f1.dd52e8
  name: Ouverture/Fermeture - Volets
  info: ''
  x: 160
  'y': 470
  wires: []
- id: 6e059c3f.301864
  type: switch
  z: f6aef2f1.dd52e8
  name: ''
  property: originalMessage.text
  propertyType: msg
  rules:
    - t: cont
      v: up
      vt: str
    - t: cont
      v: mid
      vt: str
    - t: cont
      v: down
      vt: str
    - t: else
  checkall: 'false'
  repair: false
  outputs: 4
  x: 260
  'y': 520
  wires:
    - - 6f1b9a71afbd13ec
    - - 7997e1892ec98091
    - - 8608c6bea9d4521a
    - - acc99ab81795114d
- id: a0f1b25d.56ebd8
  type: link out
  z: f6aef2f1.dd52e8
  name: ''
  links:
    - 0457c2a6501c8d96
  x: 585
  'y': 500
  wires: []
- id: 3f7706b3.bd9a5a
  type: debug
  z: f6aef2f1.dd52e8
  name: Debug
  active: false
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 620
  'y': 620
  wires: []
- id: ec21e2dfc2fb77be
  type: switch
  z: f6aef2f1.dd52e8
  name: not empty
  property: payload
  propertyType: msg
  rules:
    - t: nempty
  checkall: 'true'
  repair: false
  outputs: 1
  x: 470
  'y': 160
  wires:
    - - b52ace9b.c4f7f
- id: acc99ab81795114d
  type: function
  z: f6aef2f1.dd52e8
  name: Parse
  func: |-

    function isNumeric(n) { 
          return !isNaN(parseFloat(n)) && isFinite(n); 
    }

    if(isNumeric(msg.payload.content)) {
        var position = Number(msg.payload.content)
        return {
            payload: position
        };
    }
  outputs: 1
  noerr: 0
  initialize: ''
  finalize: ''
  libs: []
  x: 420
  'y': 620
  wires:
    - - 3f7706b3.bd9a5a
      - a0f1b25d.56ebd8
- id: 6f1b9a71afbd13ec
  type: change
  z: f6aef2f1.dd52e8
  name: up = 0
  rules:
    - t: set
      p: payload
      pt: msg
      to: '0'
      tot: num
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 420
  'y': 500
  wires:
    - - a0f1b25d.56ebd8
- id: 7997e1892ec98091
  type: change
  z: f6aef2f1.dd52e8
  name: mid = 35
  rules:
    - t: set
      p: payload
      pt: msg
      to: '35'
      tot: num
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 430
  'y': 540
  wires:
    - - a0f1b25d.56ebd8
- id: 8608c6bea9d4521a
  type: change
  z: f6aef2f1.dd52e8
  name: down = 100
  rules:
    - t: set
      p: payload
      pt: msg
      to: '100'
      tot: num
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 440
  'y': 580
  wires:
    - - a0f1b25d.56ebd8
- id: f4319bb765b32dae
  type: telegram command
  z: f6aef2f1.dd52e8
  name: /voletH
  command: /voletH
  description: ''
  registercommand: false
  language: ''
  bot: 4fc69d2d.235124
  strict: false
  hasresponse: false
  useregex: false
  removeregexcommand: false
  outputs: 1
  x: 90
  'y': 710
  wires:
    - - 6493b109d45dc1c7
- id: 6493b109d45dc1c7
  type: switch
  z: f6aef2f1.dd52e8
  name: ''
  property: originalMessage.text
  propertyType: msg
  rules:
    - t: cont
      v: up
      vt: str
    - t: cont
      v: mid
      vt: str
    - t: cont
      v: down
      vt: str
    - t: else
  checkall: 'false'
  repair: false
  outputs: 4
  x: 260
  'y': 710
  wires:
    - - 5892c03f96d976bc
    - []
    - - f3bac08e3f55f2aa
    - []
- id: 5892c03f96d976bc
  type: change
  z: f6aef2f1.dd52e8
  name: up = 0
  rules:
    - t: set
      p: payload
      pt: msg
      to: '0'
      tot: num
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 420
  'y': 700
  wires:
    - - e7e52fec716f59a2
- id: f3bac08e3f55f2aa
  type: change
  z: f6aef2f1.dd52e8
  name: down = 100
  rules:
    - t: set
      p: payload
      pt: msg
      to: '100'
      tot: num
  action: ''
  property: ''
  from: ''
  to: ''
  reg: false
  x: 440
  'y': 740
  wires:
    - - e7e52fec716f59a2
- id: e7e52fec716f59a2
  type: link out
  z: f6aef2f1.dd52e8
  name: ''
  links:
    - 4343d80627f170c9
  x: 585
  'y': 700
  wires: []
- id: 873226ce114ec6aa
  type: telegram command
  z: f6aef2f1.dd52e8
  name: /rad
  command: /rad
  description: ''
  registercommand: false
  language: ''
  bot: 4fc69d2d.235124
  strict: false
  hasresponse: false
  useregex: false
  removeregexcommand: false
  outputs: 1
  x: 90
  'y': 840
  wires:
    - - 7c59f8a6fede21fe
      - 03874918a788dc4d
- id: 7c59f8a6fede21fe
  type: switch
  z: f6aef2f1.dd52e8
  name: ''
  property: payload.content
  propertyType: msg
  rules:
    - t: cont
      v: a
      vt: str
    - t: cont
      v: c
      vt: str
    - t: cont
      v: e
      vt: str
    - t: else
  checkall: 'false'
  repair: false
  outputs: 4
  x: 260
  'y': 840
  wires:
    - - 793f6369000801a1
    - - d8336f52c2dabcac
    - - 2945bb0883a55a36
    - []
- id: 793f6369000801a1
  type: link out
  z: f6aef2f1.dd52e8
  name: ''
  links:
    - 32ea48f887dcaf01
    - 1289ec8160b383c0
  x: 395
  'y': 820
  wires: []
- id: d8336f52c2dabcac
  type: link out
  z: f6aef2f1.dd52e8
  name: ''
  links:
    - f59fd05791a47896
    - 8b59b8b09ecd5508
  x: 395
  'y': 860
  wires: []
- id: 2945bb0883a55a36
  type: link out
  z: f6aef2f1.dd52e8
  name: ''
  links:
    - b08009e947680796
    - fd31e45552eeb4e5
  x: 395
  'y': 900
  wires: []
- id: 03874918a788dc4d
  type: debug
  z: f6aef2f1.dd52e8
  name: ''
  active: true
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  statusVal: ''
  statusType: auto
  x: 260
  'y': 940
  wires: []
- id: efdc44ad7838b791
  type: debug
  z: f6aef2f1.dd52e8
  name: Status
  active: false
  tosidebar: true
  console: false
  tostatus: false
  complete: 'true'
  targetType: full
  x: 320
  'y': 200
  wires: []
- id: 2f30621f40aa8285
  type: link in
  z: f6aef2f1.dd52e8
  name: Notifications-Telegram
  links:
    - 84b1892ac15ea678
    - ecb2912f7071e62b
    - fecb20f01567e4a8
    - e7a7cb7a8df21f27
    - 0a19614dac750dc9
  x: 205
  'y': 210
  wires:
    - - e8dfc067.c65a1
