- id: 4fc69d2d.235124
  type: telegram bot
  botname: SomeKalemenaBot
  usernames: ''
  chatids: $(TELEGRAM_IN_CHATIDS)
  baseapiurl: ''
  updatemode: polling
  pollinterval: '3000'
  usesocks: false
  sockshost: ''
  socksport: '6667'
  socksusername: anonymous
  sockspassword: ''
  bothost: ''
  botpath: ''
  localbotport: '8443'
  publicbotport: '8443'
  privatekey: ''
  certificate: ''
  useselfsignedcertificate: false
  sslterminated: false
  verboselogging: true
- id: 4c23cd92.778204
  type: serial-port
  serialport: /dev/ttyJeeLink
  serialbaud: '57600'
  databits: '8'
  parity: none
  stopbits: '1'
  newline: \n
  bin: 'false'
  out: char
  addchar: false
- id: 36396f66.41717
  type: serial-port
  serialport: /dev/ttyCurrenCost
  serialbaud: '57600'
  databits: '8'
  parity: none
  stopbits: '1'
  newline: \n
  bin: 'false'
  out: char
  addchar: false
- id: c38452a5.4f84e8
  type: mqtt-broker
  name: mqtt
  broker: mqtt
  port: '1883'
  clientid: ''
  usetls: false
  protocolVersion: 4
  keepalive: '15'
  cleansession: true
  birthTopic: ''
  birthQos: '0'
  birthPayload: ''
  closeTopic: ''
  closePayload: ''
  willTopic: ''
  willQos: '0'
  willPayload: ''
- id: '26438802.204788'
  type: websocket-client
  path: 'ws://ioteleinfo.local:81'
  tls: ''
  wholemsg: 'true'
  hb: '300'
  subprotocol: ''
- id: 786c015f0b3c18d1
  type: influxdb
  hostname: victoriametrics
  port: '8428'
  protocol: http
  database: sensors
  name: sensors (VM)
  usetls: false
  tls: ''
  influxdbVersion: 1.x
  url: 'http://localhost:8086'
  rejectUnauthorized: true
