#!/bin/sh

export PATH=$PATH:/usr/local/bin:/opt/node/bin/forever:/opt/node/bin/node
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
  start)
  exec /opt/node/bin/forever --sourceDir=/opt/gpio -p /var/run/forever start server-gpio.js
  ;;

  stop)
  exec /opt/node/bin/forever stop --sourceDir=/opt/gpio server-gpio.js
  ;;
esac

exit 0
