FROM kalemena/node-red:3.0.2

RUN npm i \
        node-red-contrib-simpletime \
        node-red-contrib-moment \
        node-red-node-suncalc \
        node-red-contrib-file-function-ext \
        node-red-contrib-string \
        node-red-contrib-object-hash \
        node-red-contrib-fs \
        node-red-contrib-readdir \
        node-red-contrib-telegrambot \
        node-red-node-openweathermap \
        node-red-contrib-simple-weekly-scheduler \
        node-red-contrib-flatter \
        node-red-contrib-influxdb \
        node-red-contrib-topic-frequencies \
        node-red-node-feedparser \
        node-red-contrib-gorules@v0.0.4 \
        node-red-contrib-flow-manager
        