FROM kalemena/node-red:2.1.0

RUN npm i \
        node-red-contrib-file-function-ext \
        node-red-contrib-string \
        node-red-contrib-object-hash \
        node-red-contrib-fs \
        node-red-contrib-readdir \
        node-red-contrib-telegrambot \
        node-red-node-darksky \
        node-red-contrib-simple-weekly-scheduler \
        node-red-contrib-flatter \
        node-red-contrib-covid19 \
        node-red-contrib-influxdb \
        node-red-contrib-topic-frequencies \
        node-red-node-feedparser \
        node-red-contrib-flow-manager
        