version: '3.7'
services:

  mqtt:
    image: eclipse-mosquitto:1.6
    restart: always

  # https://github.com/marthoc/docker-deconz
  deconz:
    image: marthoc/deconz
    restart: always
    # user: "${UID}:${GID}"
    ports:
      - 7080:7080
      - 7443:7443
      - 7900:5900
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./etc/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyZigbee
    environment:
      - DECONZ_DEVICE=/dev/ttyZigbee
      - DECONZ_WEB_PORT=7080
      - DECONZ_WS_PORT=7443
      # - DECONZ_VNC_MODE=1
      # - DECONZ_VNC_PASSWORD=${ZIGBEE_DECONZ_VNC_PASSWORD:-password}
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
    extra_hosts:
      - "phoscon.de:127.0.0.1"
    networks:
      default:
        aliases:
          - deconz.tidhome.local

  nodered:
    #image: kalemena/node-red:latest
    build: ./scripts
    restart: always
    ports:
     - "${NODERED_PORT:-1880}:1880"
    volumes:
     - ./tidhome:/opt/tidhome
     - ./tidhome/config:/home/nodered/.node-red
     - ./var/log/node-red:/var/log/node-red
    # - /home/nodered/.node-red/settings.js      # Default Settings file
    # - /data/flows.json                         # Default Flows file
    devices:
     - "/dev/ttyCurrenCost:/dev/ttyCurrenCost"
     - "/dev/ttyJeeLink:/dev/ttyJeeLink"
     - "/dev/ttyZWave:/dev/ttyZWave"
    environment:
     - FLOWS=/opt/tidhome/flows/tidhome-flows.json
    env_file:
     - .env

  tools:
    image: kalemena/attestation-covid19:latest
    #volumes:
    #  - ./tidhome/data/covid/config_clement.inc:/data/config/config.inc:ro
    # ports:
    #   - 5000:5000

  web:
    image: nginx
    restart: always
    ports:
     - "80:80"
    volumes:
     - ./web/www:/usr/share/nginx/html
