version: '3.7'

networks:
  default:

volumes:
  influxdb-data:
  influxdb2-data:

services:

  mqtt:
    image: eclipse-mosquitto:1.6
    restart: always

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    restart: always
    ports:
      - "8181:8181"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./tidhome/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    privileged: true
    environment:
      - TZ=Europe/Paris
    networks:
      default:
        aliases:
          - zigbee2mqtt.tidhome.local

  influxdb:
    image: influxdb:1.8.6
    # user: "${UID}:${GID}"
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes: 
      - ./etc/influxdb/scripts:/docker-entrypoint-initdb.d
      # - ./var/lib/influxdb:/var/lib/influxdb:rw
      # - ./var/lib/.influx_history:/.influx_history
      - influxdb-data:/var/lib/influxdb:rw
    environment:
      INFLUXDB_DB: "telegraf"
      # Memory usage reduction (bugs after sometimes)
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_MONITOR_STORE_ENABLED: "false"
      INFLUXDB_META_LOGGING_ENABLED: "true"
      INFLUXDB_DATA_QUERY_LOG_ENABLED: "false"
      # Creds
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER:-default}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD:-password}
      INFLUXDB_USER: ${INFLUXDB_USER:-default}
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD:-password}

  # influxdb2:
  #   image: influxdb:2.0.7
  #   # user: "${UID}:${GID}"
  #   restart: always
  #   ports:
  #     - "9083:8083"
  #     - "9086:8086"
  #   volumes: 
  #     #- ./etc/influxdb/scripts:/docker-entrypoint-initdb.d
  #     - ./etc/influxdb2:/etc/influxdb2
  #     - influxdb2-data:/var/lib/influxdb2:rw
  #   environment:
  #     DOCKER_INFLUXDB_INIT_MODE: setup
  #     # Creds
  #     DOCKER_INFLUXDB_INIT_USERNAME: ${DOCKER_INFLUXDB_INIT_USERNAME:-default}
  #     DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD:-password}
  #     DOCKER_INFLUXDB_INIT_ORG: ${DOCKER_INFLUXDB_INIT_ORG:-tidhome-org}
  #     DOCKER_INFLUXDB_INIT_BUCKET: ${DOCKER_INFLUXDB_INIT_BUCKET:-tidhome-bucket}
  #     DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN:-secret-auth-token}
  #     # Retention
  #     DOCKER_INFLUXDB_INIT_RETENTION: ${DOCKER_INFLUXDB_INIT_RETENTION:-4w}
            
  nodered:
    #image: kalemena/node-red:latest
    build: .
    restart: always
    ports:
     - 1880
    volumes:
     - ./etc/tidhome:/etc/tidhome
     - ./tidhome:/opt/tidhome
     - ./tidhome/config:/home/nodered/.node-red
    # - ./var/log/node-red:/var/log/node-red
    # - /home/nodered/.node-red/settings.js      # Default Settings file
    # - /data/flows.json                         # Default Flows file
    devices:
     - "/dev/ttyCurrenCost:/dev/ttyCurrenCost"
     - "/dev/ttyJeeLink:/dev/ttyJeeLink"
    #  - "/dev/ttyZWave:/dev/ttyZWave"
    # environment:
    #  - FLOWS=/opt/tidhome/flows/tidhome-flows.json
    env_file:
     - .env

  gateway:
    image: nginx
    restart: always
    ports:
     - "80:80"
    volumes:
     - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
     # - ./web/www:/usr/share/nginx/html
     - /var/log/nginx:/var/log/nginx
