version: '3.7'

# networks: 
#   default: 
#     external: 
#       name: external-ti-dhome 

services:

  noderedo:
    extra_hosts:
      ioteleinfo.local: ${IOT_WEBRELAY_IP}

  nodered:
    extra_hosts:
      ioteleinfo.local: ${IOT_WEBRELAY_IP}

  gateway:
    extra_hosts:
      ioteleinfo.local: ${IOT_WEBRELAY_IP}
