version: '3.7'
services:

  # mqtt:
  #   image: eclipse-mosquitto:1.4.12
  #   restart: always
  #   ports:
  #    - "1883:1883"
  #    - "9001:9001"

  nodered:
    image: kalemena/node-red:latest
    restart: always
    ports:
     - "3880:1880"
    volumes:
     - ./src/node-red:/root/.node-red
    # devices:
    #  - "/dev/ttyCurrenCost:/dev/ttyCurrenCost"
    #  - "/dev/ttyJeeLink:/dev/ttyJeeLink"
    #  - "/dev/ttyRfxTrx:/dev/ttyRfxTrx"
    environment:
     - FLOWS=tidhome.json

  # tidhome:
  #   image: nginx
  #   restart: always
  #   ports:
  #    - "80:80"
  #   volumes:
  #    - ./src/web/www:/usr/share/nginx/html
