global:
  evaluation_interval: 1s

scrape_configs:
  - job_name: prometheus-opendtu
    scrape_interval: 30s
    static_configs: 
      - targets: [ 'http://opendtu/api/prometheus/metrics' ]
        #labels:
        #  instance: opendtu
